src/app/system/users/users-list/users-list.component.html
src/app/system/users/users-list/users-list.component.ts
src/app/system/users/users.component.ts

This PR needs the knora-ui core module from this branch: <https://github.com/dhlab-basel/Knora-ui/tree/wip/core-system-admin>

feat(admin): Show and set system admin

---

src/app/app-routing.module.ts
src/app/main/grid/grid.component.html
src/app/main/grid/grid.component.scss
src/app/main/grid/grid.component.spec.ts
src/app/main/grid/grid.component.ts
src/app/main/main.component.ts
src/app/project/board/board.component.ts
src/app/project/project.component.ts
yalc.lock

This PR needs @knora/core from develop and Knora v7.0.0

Feat: Open project from landing-page

---

src/app/user/user-form/user-form.component.ts

After adding a new user we have to update the cache with all users.
Closes #25

fix(users): Update list of users in cache

---

src/app/workspace/search/expert-search/expert-search.component.html
src/app/workspace/search/expert-search/expert-search.component.scss
src/app/workspace/search/expert-search/expert-search.component.ts

Replace expert-search form and method with the knora-ui search module expert search.
closes #31

refactor(expert-search): Add expert-search from knora-ui search module

---

src/app/app-routing.module.ts
src/app/workspace/results/results.component.html
src/app/workspace/results/results.component.ts
src/app/workspace/search/advanced-search/advanced-search.component.html
src/app/workspace/search/advanced-search/advanced-search.component.ts
src/app/workspace/search/expert-search/expert-search.component.ts

This PR works with @knora/viewer module from branch [fix/advanced-search-perform-n-queries in Knora-ui](https://github.com/dhlab-basel/Knora-ui/tree/fix/advanced-search-perform-n-queries)

fix(workspace): Reload search results

---

src/app/app-init.service.ts
src/config/config.dev.json
src/config/config.prod.json

Test with Knora-ui modules of [PR #260](https://github.com/dhlab-basel/Knora-ui/pull/263).

fix(config): Add ontologyIRI to the config

---

angular.json
src/app/main/header/header.component.html
src/app/main/header/header.component.scss
src/app/main/main.component.scss
src/app/project/collaboration/add-user/add-user.component.html
src/app/project/collaboration/add-user/add-user.component.scss
src/app/project/collaboration/collaboration.component.html
src/app/project/collaboration/collaboration.component.scss
src/app/project/project.component.html
src/app/project/project.component.scss
src/app/system/users/users-list/users-list.component.html
src/app/system/users/users-list/users-list.component.scss
src/assets/style/_responsive.scss

Improve responsive design in Kuirl.
For tablet format.

style: Improve responsive design

---

src/app/system/users/users-list/users-list.component.html

feat(users list): Disable "remove as sys admin" on own profile

---

src/app/main/main.component.html
src/app/main/main.component.ts

feat(main): Improve landing page

---

src/assets/style/_elements.scss

style: Fix position of mat-menu and box-shadow

---

.grenrc.js

chore: Update gren info

---

src/app/workspace/resource/resource.component.html

refactor(resource): Rename button Back

---

src/app/project/list/list-item-form/list-item-form.component.html
src/app/project/list/list-item-form/list-item-form.component.scss
src/app/project/list/list-item/list-item.component.html
src/app/project/list/list-item/list-item.component.scss

On large screen we had an issue with the indent of list-item form. This PR fixes this style issue

Fix style issue in lists

---

package.json
src/app/app.module.ts
src/config/config.dev.json
src/config/config.prod.json

This will solve the issue we had in --prod mode and with the api test-server configuration

Remove providers with interceptor

---

src/app/main/dialog/dialog.component.html
src/app/project/board/board.component.html
src/app/project/board/board.component.ts
src/app/project/project-form/project-form.component.ts
src/app/project/project.component.html
src/app/project/project.component.scss
src/app/system/projects/projects-list/projects-list.component.html
src/app/system/projects/projects.component.html
src/app/system/projects/projects.component.ts
src/app/system/users/users-list/users-list.component.html
src/app/system/users/users-list/users-list.component.ts
src/app/user/profile/profile.component.html
src/assets/i18n/de.json
src/assets/i18n/en.json
src/assets/style/_elements.scss

resolves #167 #174 #202 #166 
fix a part of #204

Homogenise wording

---

.circleci/config.yml
.travis.yml
src/app/project/list/list-info-form/list-info-form.component.html
src/app/project/list/list-info-form/list-info-form.component.ts
src/app/project/list/list-item-form/list-item-form.component.html
src/app/project/list/list-item-form/list-item-form.component.ts
src/app/project/list/list-item/list-item.component.ts
src/app/project/list/list.component.html
src/app/project/list/list.component.ts

Integrate Admin Lists from the lib
resolves #223 
Related to knora-ui PR[#394](https://github.com/dasch-swiss/knora-ui/pull/394)
Need fix from knora-api issue[#1559](https://github.com/dasch-swiss/knora-api/issues/1559)

Integrate admin lists

---

.circleci/config.yml
.travis.yml
README.md
package.json
src/app/project/project-form/project-form.component.ts
yarn.lock

Preparation for release 2.0.0 with the new integration of knora-api-js-lib (v0.1.1) and the new @knora module packages (v10.0.0).

Pre-release v2.0.0

---

src/app/main/help/help.component.ts

Split knora version number without extra suffix

---

src/app/main/help/help.component.ts

Fix broken link to Knora release notes page

---

yarn.lock

https://github.com/dasch-swiss/knora-app/network/alert/yarn.lock/serialize-javascript/closed

Resolve security alert about serialize-javascript

---

src/app/main/cache/cache.service.spec.ts
src/app/main/cookie-policy/cookie-policy.component.spec.ts
src/app/main/error/error.component.spec.ts
src/app/main/footer/footer.component.spec.ts
src/app/main/header/header.component.spec.ts
src/app/main/help/help.component.spec.ts
src/app/main/login/login.component.spec.ts
src/app/main/main.component.spec.ts
src/app/project/board/board.component.spec.ts
src/app/project/collaboration/add-user/add-user.component.spec.ts
src/app/project/collaboration/collaboration.component.spec.ts
src/app/project/collaboration/select-group/select-group.component.spec.ts
src/app/project/project-form/project-form.component.spec.ts
src/app/project/project.component.spec.ts
src/app/system/projects/projects.component.spec.ts
src/app/system/system.component.spec.ts
src/app/system/users/users.component.spec.ts
src/app/user/account/account.component.spec.ts
src/app/user/dashboard/dashboard.component.spec.ts
src/app/user/profile/profile.component.spec.ts
src/app/user/user-form/user-form.component.spec.ts
src/app/user/user-menu/user-menu.component.spec.ts

Todo list of unit tests has been added to each spec files ([following the list of issue nr.253](https://github.com/dasch-swiss/knora-app/issues/253)).

Add todo list in spec files

---

src/app/app-global.ts
src/app/main/help/help.component.ts
src/app/main/main.component.html
src/app/main/main.component.spec.ts
src/app/main/main.component.ts
src/app/project/collaboration/collaboration.component.html
src/app/system/users/users-list/users-list.component.html
src/app/system/users/users-list/users-list.component.ts
src/app/user/profile/profile.component.html
src/app/user/user-form/password-form/password-form.component.html
src/assets/i18n/en.json

closes #131 
closes #219 
closes #214 
closes #209 
closes #200

Fix wording through Knora-app

---

README.md
package-lock.json
src/app/main/dialog/dialog.component.html
src/app/main/help/help.component.ts
src/app/main/main.component.html
src/app/main/main.component.ts

closes [DSP-608](https://dasch.myjetbrains.com/youtrack/issue/DSP-608)

Replace the term source by resource

---

.github/workflows/main.yml
.grenrc
CHANGELOG.md
Makefile
README.md
package-lock.json

Resolves [DSP-420](https://dasch.myjetbrains.com/youtrack/issue/DSP-420)

DSP-420 update release process

---

.github/release-drafter.yml
.github/workflows/main.yml

Resolves part of [dsp-617](https://dasch.myjetbrains.com/youtrack/issue/DSP-617)

DSP-617 Use release-drafter instead gren

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/testing-bug.md
README.md
package-lock.json
src/config/config.prod.json
vars.mk

Resolves [DSP-679](https://dasch.myjetbrains.com/youtrack/issue/DSP-679)
- Clean up the github issue templates which should be used by extern reports.
- Fix security issue
- Update prod-config example
- No dirty tag in docker image: This is a temporary solution and will be updated as soon we use bazel everywhere.
- Update badges in README

Fix tiny issues

---

src/app/main/header/header.component.html
src/app/main/header/header.component.scss

resolves [DSP-371](https://dasch.myjetbrains.com/youtrack/issue/DSP-371)

DSP-371 - Improve the visibility of expert and advanced search links

---

src/app/main/help/help.component.ts

resolves [DSP-666](https://dasch.myjetbrains.com/youtrack/issue/DSP-666)

DSP-666 Fix issue with version number

---

.github/pull_request_template.md

resolves [DSP-699](https://dasch.myjetbrains.com/youtrack/issue/DSP-699)
I followed this documentation:
https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
We can test it, when it's merged into master and next time we create a new PR here.

DSP-669 Add template for PRs

---

src/app/main/dialog/dialog-header/dialog-header.component.html
src/app/main/dialog/dialog.component.html
src/app/main/help/help.component.ts
src/app/user/user-form/password-form/password-form.component.html

resolves [DSP-368](https://dasch.myjetbrains.com/youtrack/issue/DSP-368)

DSP-368 - Redundancy with Cancel button and close button in dialog boxes

---

src/assets/style/_responsive.scss

resolves [DSP-689](https://dasch.myjetbrains.com/youtrack/issue/DSP-689)

DSP-689 Resource viewer fix style in properties toolbar

---

src/app/main/header/header.component.html
src/app/main/header/header.component.scss
src/app/main/header/header.component.ts
src/assets/style/_config.scss
src/assets/style/_elements.scss

resolves [DSP-284](https://dasch.myjetbrains.com/youtrack/issue/DSP-284)

DSP-284 Display app version in header

---

src/app/main/select-language/select-language.component.ts

resolves [DSP-766](https://dasch.myjetbrains.com/youtrack/issue/DSP-766)

DSP-766 Remove 'de' from list of available languages

---

src/app/app.module.ts
src/app/main/directive/external-links.directive.spec.ts
src/app/main/directive/external-links.directive.ts
src/assets/style/_elements.scss

resolves [DSP-297](https://dasch.myjetbrains.com/youtrack/issue/DSP-297)
developed with dsp-api v13.0.0-rc.16
for testing: check the footer and the Help page

DSP-297 - Make the external links easy to spot

---

src/app/main/footer/footer.component.html
src/app/main/main.component.html

On landing page, update contact information for:
- email address with default subject
- post address
- phone number
resolves [DSP-293](https://dasch.myjetbrains.com/youtrack/issue/DSP-293)

DSP-293 Update contact information on the landing page

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/app/project/ontology/ontology.component.html
src/app/project/ontology/resource-class-form/resource-class-form.component.ts

- Update README
- Update CHANGELOG
- Update js-lib to version 1.0.0-rc.13
- Update ui-lib to version 1.0.0-rc.9

Update js-lib and ui-lib

---

src/app/project/ontology/ontology-form/ontology-form.component.ts
src/app/project/ontology/ontology.component.html
src/app/project/ontology/ontology.component.ts

resolves [DSP-859](https://dasch.myjetbrains.com/youtrack/issue/DSP-859)

DSP-859 Create ontology

---

src/app/system/projects/projects-list/projects-list.component.ts

resolves [DSP-908](https://dasch.myjetbrains.com/youtrack/issue/DSP-908)

DSP-908 - Project List Sorting Fix

---

src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.ts
src/app/workspace/resource/resource-instance-form/select-project/select-project.component.spec.ts
src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts
src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts

DSP-1062 - Form "back" button functionality polish

---

package-lock.json
package.json
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts

DSP-1098 - Bump JS-Lib Version and Fix Breaking Changes

---

src/app/main/header/header.component.ts
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html

DSP-1127 Rename header titles and resource placeholders

---

src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss

DSP-1136 - Select-Properties Component CSS Quick Fix

---

src/app/project/board/board.component.ts

DSP-694 Bug fix in project view when not logged-in

---

src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.html
src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.spec.ts
src/app/workspace/resource/resource-instance-form/select-project/select-project.component.html
src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html

DSP-1161 Add error handling in the new resource form

---

.github/workflows/main.yml
.gitignore
package-lock.json
package.json
vars.mk

resolves DSP-1168
- Bring back an empty changelog file. This will be updated by "release please action" after merging this PR
- Add "release please action" and remove "release drafter"

Wip/dsp 1168 Release please action instead release drafter

---

package-lock.json

The release-please-action was not yet happy with my previous PR. Next time I have to read carefully my own documentation 🙈 to write the correct commit message --> <https://docs.dasch.swiss/developers/dsp/contribution/#commit-message-format>
I hope this PR will force our release PR to update to v3.0.0

Prepare next big release

---

.github/workflows/main.yml

Update package-name in gh actions workflow

---

.github/pull_request_template.md

chore: update pr template (DSP-1189)

---

package-lock.json
package.json

Update:
- dsp-ui to v1.1.1
- dsp-js to v.1.1.0

chore: update the dsp-ui and dsp-js versions to the latest

---

Makefile

fix (publish): add to explicitly push all tags

---

src/app/project/ontology/property-info/property-info.component.spec.ts
src/app/project/ontology/property-info/property-info.component.ts

fix(ontology): bug fix in list property (DSP-1368)

---

.github/workflows/main.yml
docs/how-to-contribute/index.md
src/app/main/directive/base-value.directive.ts
src/app/main/directive/invalid-control-scroll.directive.ts
src/app/main/error/error.component.ts
src/app/main/header/header.component.ts
src/app/main/help/help.component.ts
src/app/main/main.component.ts
src/app/material-module.ts
src/app/project/board/attribution-tab-view/attribution-tab-view.component.ts
src/app/project/ontology/default-data/default-resource-classes.ts
src/app/project/ontology/ontology-form/ontology-form.component.ts
src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.ts
src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.ts
src/app/project/ontology/ontology.component.ts
src/app/project/ontology/property-form/property-form.component.ts
src/app/project/ontology/property-info/property-info.component.spec.ts
src/app/project/ontology/property-info/property-info.component.ts
src/app/project/ontology/resource-class-form/resource-class-form.component.ts
src/app/project/ontology/resource-class-form/resource-class-form.service.ts
src/app/system/projects/projects.component.ts
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
src/app/workspace/resource/resource.component.ts
src/tslint.json

refactor(tslint): use lint and refactor code (DSP-1369)

---

.github/workflows/main.yml

chore(gh-ci): update release please configuration (DSP-1381)

---

src/app/project/board/board.component.ts

fix(project): disable error handler in metadata request (DSP-1395)

---

src/app/main/dialog/dialog.component.html

fix(ontology): Bug fix in ontology form (DSP-1526)

---

src/app/project/ontology/ontology-form/ontology-form.component.ts

fix(ontology): bug fix in create ontology process (DSP-1558)

---

src/app/project/collaboration/add-user/add-user.component.ts
src/app/project/project-form/project-form.component.ts
src/app/user/user-form/user-form.component.ts

fix(project): bug fix in project member management (DSP-1563)

---

src/app/project/ontology/default-data/default-properties.ts

refactor(ontology): rename boolean prop type (DSP-1561)

---

src/app/project/list/list.component.spec.ts
src/app/project/list/list.component.ts

fix(list): list deletion

---

src/app/project/ontology/default-data/default-resource-classes.ts

refactor(ontology): disable rti image class (DSP-1559)

---

package-lock.json
src/app/app-routing.module.ts
src/app/main/header/header.component.html

resolves DSP-1570
The branch was checked-out from the `develop` branch and updated from the `main` branch

feat(DMP): bring back the workspace

---

package-lock.json
package.json

feat(search): specify linked resource in advanced search (DSP-1661)

---

src/index.html

chore(analytics): add fathom

---

mkdocs.yml

docs(user-guide): fix navigation links

---

package-lock.json
package.json
src/config/config.dev.json
src/config/config.prod.json

resolves DSP-1672
This PR contains the [latest version of DSP-UI (v1.6.0)](https://github.com/dasch-swiss/dsp-ui-lib/releases/tag/v1.6.0) with important improvements of some property value components. One of those components needs a new config param. This will be a breaking change because we have to update the config in the ops-infra as well.

feat(config)!: add geoname config (DSP-1672)

---

src/app/workspace/resource/properties/properties.component.html
src/app/workspace/resource/properties/properties.component.ts

chore(resource): hide file value in properties (DSP-1261)

---

package-lock.json
package.json

chore(deps): bump dsp-ui to latest version (DSP-1838)

---

package-lock.json
package.json
src/assets/style/_elements.scss

Should be the last update of DSP-UI

chore(deps): bump dsp-ui to latest

---

src/app/app.module.ts
src/app/main/cache/cache.service.spec.ts
src/app/main/error/error-handler.service.spec.ts
src/app/project/board/board.component.spec.ts
src/app/project/collaboration/add-user/add-user.component.spec.ts
src/app/project/collaboration/collaboration.component.spec.ts
src/app/project/collaboration/select-group/select-group.component.spec.ts
src/app/project/list/list-info-form/list-info-form.component.spec.ts
src/app/project/list/list.component.spec.ts
src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.spec.ts
src/app/project/ontology/ontology.component.spec.ts
src/app/project/project-form/project-form.component.spec.ts
src/app/project/project.component.spec.ts
src/app/system/projects/projects-list/projects-list.component.spec.ts
src/app/system/projects/projects.component.spec.ts
src/app/system/users/users-list/users-list.component.spec.ts
src/app/system/users/users.component.spec.ts
src/app/user/account/account.component.spec.ts
src/app/user/dashboard/dashboard.component.spec.ts
src/app/user/membership/membership.component.spec.ts
src/app/user/profile/profile.component.spec.ts
src/app/user/user-form/password-form/password-form.component.spec.ts
src/app/user/user-form/user-form.component.spec.ts
src/app/user/user-menu/user-menu.component.spec.ts
src/app/user/user.component.spec.ts
src/app/workspace/resource/project.service.spec.ts
src/app/workspace/resource/resource.component.spec.ts
src/app/workspace/results/results.component.spec.ts
src/app/workspace/search/search-panel/search-panel.component.html

refactor: remove CoreModule dependency (DSP-1884)

---

src/app/app.component.spec.ts
src/app/app.module.ts
src/app/main/header/header.component.spec.ts

refactor: remove SearchModule dependency (DSP-1888)

---

src/app/app.module.ts
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.spec.ts
src/app/workspace/resource/resource.component.spec.ts
src/app/workspace/results/results.component.spec.ts

refactor: remove ViewerModule dependency (DSP-1890)

---

package-lock.json
src/app/workspace/resource/operations/display-edit/display-edit.component.html
src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
src/assets/style/_elements.scss
src/assets/style/main.scss

style: refactor style after moving dsp-ui to the app (DSP-1894)

---

package-lock.json
src/app/workspace/resource/operations/display-edit/display-edit.component.html
src/app/workspace/resource/operations/display-edit/display-edit.component.ts
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.ts

feat: support textarea (DSP-1896)

---

src/app/workspace/resource/resource.component.ts

fix(annotations): fix annotations refresh bug (DSP-1907)

---

src/app/workspace/results/list-view/list-view.component.spec.ts
src/app/workspace/results/list-view/list-view.component.ts

fix: gravsearch results don't appear after page refresh (DSP-1675)

---

package-lock.json
package.json

chore(deps): use release of ckeditor custom build (DEV-189)

---

src/app/main/error/error-handler.service.ts

fix(error): resolve error handler in case of server error (DEV-205)

---

src/app/project/ontology/ontology-form/ontology-form.component.ts

fix(ontology): send modified label (DEV-221)

---

src/app/workspace/results/list-view/resource-grid/resource-grid.component.html
src/app/workspace/results/list-view/resource-list/resource-list.component.html
src/app/workspace/results/list-view/resource-list/resource-list.component.scss
src/assets/style/_elements.scss

fix(results): display xml in a better way (DEV-96)

---

package-lock.json
package.json
src/app/workspace/resource/operations/add-value/add-value.component.ts
src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.ts

fix(value): bug fix in text-value-as-string (DEV-242)

---

Dockerfile

build: bump version of base nginx image (DEV-263)

---

src/app/project/ontology/ontology-form/ontology-form.component.html
src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
src/app/project/ontology/ontology-form/ontology-form.component.ts

fix(ontology): bug fix in ontology form (DEV-280)

---

src/app/workspace/resource/resource.component.ts

fix(resource): create resource iri from route only in certain cases (DEV-306)

---

Dockerfile

chore(deps): use correct nginx-server (DEEV-263)

---

src/app/workspace/resource/resource.component.ts

fix(archive representation): display resource with archive representation (DEV-354)

---

src/app/project/ontology/ontology.service.ts

fix(ontology-editor): display sub-properties the correct way (DEV-530)

---

src/app/workspace/search/services/gravsearch-generation.service.ts

fix(gravsearch): Gravsearch imprecise dates (DEV-573)

---

package-lock.json
package.json
src/app/workspace/resource/operations/display-edit/display-edit.component.html
src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.html

fix(value): do not use linkify in text value as html (DEV-563)

---

src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.ts

feat(advanced-search): support subclasses in cross-resource query (DEV-487)

---

.github/workflows/main.yml
package-lock.json
src/app/main/error/error-handler.service.spec.ts

I had to exclude a test that was causing problems in Github Actions. I also cleaned up the workflow and updated dependent packages.

refactor: clean up code, tests and packages

---

docs/requirements.txt

fix(mkdocs): update mkdocs to 1.3.0 (DEV-736)

---

src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html

fix(text-value-as-string): links in text values (DEV-797)

---

src/app/workspace/resource/resource.component.ts

fix(representation): disable progress indicator correctly (DEV-905)

---

docs/user-guide/data.md
src/app/app.module.ts
src/app/main/action/hint/hint.component.html
src/app/main/action/hint/hint.component.scss
src/app/main/action/hint/hint.component.spec.ts
src/app/main/action/hint/hint.component.ts
src/app/main/grid/grid.component.scss
src/app/workspace/results/list-view/list-view.component.html
src/app/workspace/results/list-view/list-view.component.scss
src/app/workspace/search/fulltext-search/fulltext-search.component.html
src/app/workspace/search/search-panel/search-panel.component.html
src/app/workspace/search/search-panel/search-panel.component.scss
src/app/workspace/search/search-panel/search-panel.component.ts
src/assets/style/_elements.scss
src/assets/style/_responsive.scss
src/assets/style/_search.scss

feat(hint): display hint about fulltext search (DEV-901)

---

src/app/project/ontology/resource-class-info/resource-class-info.component.html
src/app/project/ontology/resource-class-info/resource-class-info.component.ts

feat(resource): open resource instances from ontology class (DEV-950)

---

src/app/project/ontology/property-form/property-form.component.ts
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.spec.ts
src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.ts
src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-resource-class/search-select-resource-class.component.spec.ts

chore(classes): sort resource classes by label (DEV-952)

---

src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts
src/app/workspace/resource/values/link-value/link-value.component.ts

fix(link-value): list resource classes from all ontologies in project (DSP-1034)

---

README.md

docs (README): Update broken links of the main README file (DEV-1045)

---

src/app/workspace/resource/values/link-value/link-value.component.ts

resolves DEV-1034
this is a hotfix to add back some code that was accidentally removed

fix(link-value): hotfix - add onto iri to api request (DEV-1034)

---

src/app/app-routing.module.ts
src/app/main/action/login-form/login-form.component.ts
src/app/main/status/status.component.spec.ts
src/app/project/project.component.ts

refactor(routing): home button should direct to overview page (DEV-1152)

---

src/app/main/services/notification.service.ts

fix(notification): Notifications only appearing for a split second (DEV-1093)

---

src/app/project/ontology/ontology.component.html

fix(ontology): fix 403 error incorrectly appearing on page (DEV-1323)

---

src/app/project/project.component.ts

fix(project): fix route to lists (DEV-1369)

---

src/app/project/ontology/ontology.component.spec.ts

test(ontology): fix tests (DEV-1376)

---

src/app/workspace/resource/representation/upload/upload.component.scss
src/app/workspace/resource/representation/upload/upload.component.spec.ts
src/app/workspace/resource/representation/upload/upload.component.ts

fix(upload): convert file extensions to lowercase before checking for validity (DEV-1391)

---

src/app/project/list/list-info-form/list-info-form.component.ts

fix(list-info-form): fix project iri generation (DEV-1387)

---

src/app/main/action/string-literal-input/string-literal-input.component.ts
src/app/main/grid/grid.component.html
src/app/main/pipes/formatting/knoradate.pipe.ts
src/app/main/pipes/string-transformation/stringify-string-literal.pipe.ts
src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts
src/app/project/list/list-item-form/list-item-form.component.ts
src/app/workspace/resource/representation/archive/archive.component.ts
src/app/workspace/resource/representation/audio/audio.component.ts
src/app/workspace/resource/representation/document/document.component.ts
src/app/workspace/resource/representation/still-image/still-image.component.ts
src/app/workspace/resource/representation/text/text.component.ts
src/app/workspace/resource/representation/video/video.component.ts
src/app/workspace/resource/values/date-value/date-picker/date-picker.component.ts
src/app/workspace/resource/values/list-value/list-value.component.ts
src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/search-list-value/search-list-value.component.ts

refactor: replace substr with substring (DEV-1409)

---

src/app/workspace/resource/values/list-value/list-value.component.ts

fix(list-value): fix payload for API request to update a link value (DEV-1420)

---

src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html

chore (mat-label): rename mat-label of select

---

src/app/project/ontology/resource-class-form/resource-class-form.component.ts
src/assets/style/_ontology.scss

fix(css): adjust css of form error message (DEV-1458)

---

src/app/project/ontology/ontology.component.ts

fix(ontology): list of class properties sometimes not loading correctly (DEV-1435)

---

src/app/workspace/resource/values/link-value/link-value.component.spec.ts
src/app/workspace/resource/values/link-value/link-value.component.ts
src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/search-link-value/search-link-value.component.spec.ts
src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/search-link-value/search-link-value.component.ts

feat(link-value, search-link-value): add debouncing to search requests (DEV-1463)

---

src/app/workspace/results/list-view/list-view.component.html
src/app/workspace/results/list-view/list-view.component.scss
src/app/workspace/results/list-view/list-view.component.ts
src/assets/style/_config.scss

feat(list-view): list-view redesign (DEV-1461)

---

src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts
src/app/project/list/list-item/list-item.component.ts
src/app/workspace/results/list-view/list-view.component.html
src/app/workspace/results/list-view/list-view.component.scss
src/app/workspace/results/list-view/list-view.component.ts

fix(result): No results message (DEV-1455)

---

src/app/workspace/resource/operations/display-edit/display-edit.component.html
src/app/workspace/resource/operations/display-edit/display-edit.component.ts
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html

refactor(text-value-as-string): no longer account for richText gui attribute (DEV-1471)

---

src/app/workspace/resource/properties/properties.component.ts
src/app/workspace/resource/resource.component.ts
src/app/workspace/resource/services/incoming.service.ts

resolves DEV-1493
Sorry I messed up the branch name. To recreate the bug you need to:
- Import the json below with dsp-tools
- Add a property to the book resource that links to pages
- Create 2 pages, a manuscript and 2 books (linked to 1 page each)
- View the manuscript and go to the pages tab
{
"prefixes": {
"healingarts": "http://api.test.dasch.swiss/ontology/083E/healingarts/v2",
"dcterms": "http://purl.org/dc/terms/"
},
"$schema": "https://raw.githubusercontent.com/dasch-swiss/dsp-tools/main/knora/dsplib/schemas/ontology.json",
"project": {
"shortcode": "083E",
"shortname": "healingarts",
"longname": "Healing Arts. Representations and Practices of Medical Knowledge in Art and Literature (9th-12th centuries)",
"descriptions": {
"en": "The extent to which art and literature enter into …

fix(properties): fixing incoming links bug in compound view (DEV-1493)

---

src/app/workspace/resource/values/link-value/link-value.component.ts

bug(resource): res references to itself

---

src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.html
src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.scss
src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts
src/app/project/project.component.html
src/app/project/project.component.scss
src/app/workspace/resource/operations/display-edit/display-edit.component.html
src/app/workspace/resource/operations/display-edit/display-edit.component.ts
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html

resolves DEV-1454
**New design of the side-nav**

style(side-nav): redesign of side navigator (DEV-1454)

---

src/app/project/ontology/ontology.component.ts
src/app/project/ontology/resource-class-info/resource-class-info.component.ts

fix(ontology): Displaying ontology on click (DEV-1545)

---

src/app/workspace/search/fulltext-search/fulltext-search.component.spec.ts
src/app/workspace/search/fulltext-search/fulltext-search.component.ts

fix(fulltext-search): don't allow search queries of less than 3 characters (DEV-1602)

---

src/app/project/project.component.html
src/app/project/project.component.scss
src/app/project/project.component.ts

fix(project): Prevent adding new data model for deactivated projects (DEV-1582)

---

src/index.html

feat(releasenotes): Integrate releasenotes (DEV-1600)

---

src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.spec.ts
src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts

fix(create-link-resource): fix issue when creating a new linked resource (DEV-1637)

---

src/app/project/ontology/ontology.component.scss
src/app/project/ontology/property-info/property-info.component.html
src/app/project/ontology/property-info/property-info.component.spec.ts

style(ontology editor): restyle ontology editor for cardinalities (DEV-1614)

---

src/app/project/project.component.html
src/app/project/project.component.scss
src/app/project/project.component.ts
src/assets/style/_layout.scss
src/assets/style/main.scss

feat(project): add button to collapse/expand sidenav (DEV-1535)

---

src/app/main/action/login-form/login-form.component.html
src/app/main/dialog/dialog.component.html
src/app/main/header/header.component.html
src/app/project/board/board.component.html
src/app/project/ontology/ontology-form/ontology-form.component.html
src/app/project/ontology/property-form/property-form.component.html
src/app/project/ontology/resource-class-form/resource-class-form.component.html
src/app/project/project-form/project-form.component.html
src/app/system/project-tile/project-tile.component.html
src/app/system/project-tile/project-tile.component.spec.ts
src/app/system/projects/projects-list/projects-list.component.html
src/app/system/users/users-list/users-list.component.html
src/app/user/account/account.component.html
src/app/user/overview/overview.component.html
src/app/user/profile/profile.component.html
src/app/user/user-form/password-form/password-form.component.html
src/app/user/user-form/user-form.component.html
src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.html
src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.spec.ts
src/app/workspace/resource/representation/still-image/still-image.component.html
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
src/app/workspace/resource/resource-link-form/resource-link-form.component.html
src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/search-select-property.component.html

fix: fix disappeared buttons colors (DEV-1686)

---

src/app/main/action/hint/hint.component.ts

fix: adapt link to search doc

---

src/app/project/project.component.html

fix(project): disable closing sidenav with esc key (DEV-1687)

---

src/app/system/projects/projects-list/projects-list.component.ts
src/app/user/membership/membership.component.html
src/app/user/membership/membership.component.ts

feat(projects-list): system admin cleanup (DEV-1457)

---

.github/workflows/publish-from-branch.yml

chore: make possible to publish manually to DockerHub using GH Actions

---

src/app/main/dialog/dialog.component.html
src/app/main/header/header.component.html
src/app/main/header/header.component.ts
src/app/main/services/component-communication-event.service.ts
src/app/project/beta/ontology-classes/ontology-class-instance/ontology-class-instance.component.html
src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts
src/app/project/ontology/resource-class-info/resource-class-info.component.html
src/app/project/ontology/resource-class-info/resource-class-info.component.ts
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts

refactor(resource-instance-form): refactor resource instance form (DEV-1460)

---

.github/workflows/main.yml
.github/workflows/publish-from-branch.yml
Dockerfile
Makefile

chore: enable publishing docker image arm64 and amd64 architectures (DEV-1701)

---

src/app/system/project-tile/project-tile.component.html
src/app/system/project-tile/project-tile.component.scss
src/app/user/overview/overview.component.html
src/app/user/overview/overview.component.scss
src/app/workspace/resource/representation/representation.service.ts

feat(home-page): Changes to homepage (DEV-1450)

---

src/app/main/action/string-literal-input/string-literal-input.component.html
src/app/main/action/string-literal-input/string-literal-input.component.ts
src/app/project/list/list-info-form/list-info-form.component.html
src/app/project/list/list-info-form/list-info-form.component.ts

fix(lists): error messages only appear after focus (DEV-1692)

---

src/app/project/ontology/property-form/property-form.component.html
src/app/project/ontology/property-form/property-form.component.ts

fix(cardinalities): wrong user feedback before correct one (DEV-1971)

---

src/app/project/ontology/property-form/property-form.component.html
src/app/project/ontology/property-form/property-form.component.ts

…for newly assigned properties
resolves DEV-1790

fix(cardinalities): enable the required toggle programmatically (DEV-1790)

---

src/app/workspace/resource/resource.component.html
src/app/workspace/resource/resource.component.scss
src/app/workspace/resource/resource.component.ts

feat(resource): Restricted view message (DEV-1456)

---

src/app/main/dialog/dialog.component.html
src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.html
src/app/project/list/list-item-form/list-item-form.component.html
src/app/project/list/list-item/list-item.component.html
src/app/project/ontology/ontology-form/ontology-form.component.html
src/app/project/project-form/project-form.component.html
src/app/user/dashboard/dashboard.component.html
src/app/user/profile/profile.component.html
src/app/user/user-form/password-form/password-form.component.html
src/app/user/user-form/user-form.component.html
src/app/workspace/resource/values/date-value/date-picker/date-picker.component.html
src/app/workspace/search/advanced-search/advanced-search.component.html
src/app/workspace/search/expert-search/expert-search.component.html

style(app): change to primary (DEV-1865)

---

src/app/app-init.service.ts
src/assets/style/_theme.scss

style: add default background color to release badge (DEV-1918)

---

.github/workflows/main.yml
.github/workflows/publish-from-branch.yml
Dockerfile

build: add node to jobs publishing docker images

---

apps/dsp-app/src/app/user/overview/overview.component.scss

style: fix overview page bottom padding

---

apps/dsp-app/src/app/user/overview/overview.component.scss

style: overview component bottom padding

---

.github/workflows/main.yml

build(ci): add publish on commit  or tag (release) on main

---

apps/dsp-app/src/app/user/user-form/user-form.component.html

fix: no autocomplete for username

---

apps/dsp-app/src/app/material-module.ts
apps/dsp-app/src/app/project/ontology/ontology.component.spec.ts
apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-info.component.html
apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-info.component.scss
apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.html
apps/dsp-app/src/app/system/users/users-list/users-list.component.html
apps/dsp-app/src/app/user/membership/membership.component.html
apps/dsp-app/src/app/user/user-form/password-form/password-form.component.html
apps/dsp-app/src/app/workspace/resource/properties/properties.component.html
apps/dsp-app/src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
apps/dsp-app/src/assets/style/_elements.scss
apps/dsp-app/src/assets/style/_layout.scss
apps/dsp-app/src/assets/style/main.scss

chore: angular mdc migration - card

---

apps/dsp-app/src/app/user/user-menu/user-menu.component.ts

fix(user menu): bypass cache; get user from the api and set in cache (DEV-2024)

---

.github/workflows/main.yml

fix(CD): get tag before changes happen (INFRA-241)

---

apps/dsp-app/src/app/user/overview/overview.component.scss

resolves DEV-2021
before:
after:

fix: padding on both sides

---

apps/dsp-app/src/app/user/account/account.component.ts
apps/dsp-app/src/app/user/profile/profile.component.ts
apps/dsp-app/src/app/user/user-form/password-form/password-form.component.html
apps/dsp-app/src/app/user/user-form/password-form/password-form.component.scss
apps/dsp-app/src/app/user/user-form/password-form/password-form.component.spec.ts
apps/dsp-app/src/app/user/user-form/password-form/password-form.component.ts
apps/dsp-app/src/app/user/user-form/user-form.component.ts

fix: app breaks when on /account route

---

apps/dsp-app/.eslintrc.json
apps/dsp-app/src/app/main/directive/external-links.directive.ts
apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.spec.ts
apps/dsp-app/src/app/project/ontology-classes/ontology-classes.component.spec.ts
apps/dsp-app/src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.spec.ts
apps/dsp-app/src/app/workspace/resource/operations/display-edit/display-edit.component.spec.ts
apps/dsp-app/src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.spec.ts
apps/dsp-app/src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
apps/dsp-app/src/app/workspace/resource/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts

chore: adjust linter rules for dsp-app

---

apps/dsp-app/src/app/system/project-tile/project-tile.component.html
apps/dsp-app/src/app/system/project-tile/project-tile.component.spec.ts
apps/dsp-app/src/app/system/project-tile/project-tile.component.ts
apps/dsp-app/src/app/user/overview/overview.component.html
apps/dsp-app/src/app/user/overview/overview.component.spec.ts
apps/dsp-app/src/app/user/overview/overview.component.ts
apps/dsp-app/src/app/workspace/search/services/gravsearch-generation.service.spec.ts

refactor: overview and project tile refactor

---

apps/dsp-app/src/app/main/action/progress-indicator/progress-indicator.component.ts
apps/dsp-app/src/app/main/action/sort-button/sort-button.component.ts
apps/dsp-app/src/app/main/cookie-policy/cookie-policy.component.ts
apps/dsp-app/src/app/main/dialog/dialog-header/dialog-header.component.ts
apps/dsp-app/src/app/main/dialog/dialog.component.ts
apps/dsp-app/src/app/main/footer/footer.component.ts
apps/dsp-app/src/app/main/grid/grid.component.ts
apps/dsp-app/src/app/main/select-language/select-language.component.ts
apps/dsp-app/src/app/project/permission/add-group/add-group.component.ts
apps/dsp-app/src/app/project/settings/settings.component.ts
apps/dsp-app/src/app/system/groups/groups-list/groups-list.component.ts
apps/dsp-app/src/app/system/groups/groups.component.ts
apps/dsp-app/src/app/user/collection-list/collection-list.component.ts
apps/dsp-app/src/app/workspace/intermediate/intermediate.component.ts
apps/dsp-app/src/app/workspace/search/search-panel/search-panel.component.spec.ts
apps/dsp-app/src/app/workspace/search/search-panel/search-panel.component.ts

chore(unused lifecycle hooks): remove unused lifecycle hooks

---

apps/dsp-app/src/app/workspace/resource/values/custom-regex.ts

fix(app): top-level-domain with 63 chars

---

apps/dsp-app/src/app/workspace/resource/operations/display-edit/display-edit.component.html
apps/dsp-app/src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
apps/dsp-app/src/app/workspace/resource/values/boolean-value/boolean-value.component.html
apps/dsp-app/src/app/workspace/resource/values/boolean-value/boolean-value.component.scss
apps/dsp-app/src/app/workspace/resource/values/boolean-value/boolean-value.component.ts
apps/dsp-app/src/app/workspace/resource/values/comment-form/comment-form.component.html
apps/dsp-app/src/app/workspace/resource/values/comment-form/comment-form.component.ts

feat(boolean values): implement removal of boolean values

---

apps/dsp-app/src/app/workspace/resource/values/date-value/date-picker/date-picker.component.ts
package-lock.json

fix(app): button activated for date search

---

apps/dsp-app/src/app/material-module.ts
package-lock.json

refactor(app): delete unused module

---

apps/dsp-app/src/app/material-module.ts

refactor(app): delete unused MatTable module

---

Dockerfile
libs/vre/shared/app-logging/src/lib/app-logging/app-logging.service.ts

refactor: improve logging

---

apps/dsp-app/src/app/material-module.ts
apps/dsp-app/src/app/project/project.component.spec.ts
apps/dsp-app/src/app/project/settings/settings.component.html
apps/dsp-app/src/app/project/settings/settings.component.spec.ts
apps/dsp-app/src/app/system/system.component.html
apps/dsp-app/src/app/system/system.component.spec.ts
apps/dsp-app/src/app/user/user.component.html
apps/dsp-app/src/app/user/user.component.spec.ts
apps/dsp-app/src/app/workspace/resource/resource.component.ts
apps/dsp-app/src/styles/_elements.scss
apps/dsp-app/src/styles/_layout.scss

chore: angular mdc migration tabs

---

apps/dsp-app/src/app/main/dialog/dialog.component.spec.ts
apps/dsp-app/src/app/material-module.ts
apps/dsp-app/src/app/project/description/description.component.spec.ts
apps/dsp-app/src/app/project/ontology/property-form/property-form.component.scss
apps/dsp-app/src/app/project/ontology/resource-class-form/resource-class-form.component.spec.ts
apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/resource-class-property-info.component.spec.ts
apps/dsp-app/src/app/user/user-form/user-form.component.spec.ts
apps/dsp-app/src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/search-select-property.component.spec.ts

chore: angular mdc migration slide toggle

---

apps/dsp-app/src/app/main/header/header.component.spec.ts
apps/dsp-app/src/app/material-module.ts

chore: angular mdc migration progress bar

---

apps/dsp-app/src/app/workspace/resource/representation/video/video.component.ts

fix(freezing): app freeze if sipi does not respond (DEV-1562)

---

apps/dsp-app/src/app/workspace/resource/representation/archive/archive.component.spec.ts
apps/dsp-app/src/app/workspace/resource/representation/archive/archive.component.ts
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.spec.ts
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.ts
apps/dsp-app/src/app/workspace/resource/representation/document/document.component.html
apps/dsp-app/src/app/workspace/resource/representation/document/document.component.spec.ts
apps/dsp-app/src/app/workspace/resource/representation/document/document.component.ts
apps/dsp-app/src/app/workspace/resource/representation/representation.service.ts
apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.ts
apps/dsp-app/src/app/workspace/resource/representation/text/text.component.spec.ts
apps/dsp-app/src/app/workspace/resource/representation/text/text.component.ts

fix(freeze): Remove/replace freezing request

---

apps/dsp-app/src/app/workspace/resource/representation/archive/archive.component.html
apps/dsp-app/src/app/workspace/resource/representation/archive/archive.component.scss
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.html
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.scss
apps/dsp-app/src/app/workspace/resource/representation/document/document.component.html
apps/dsp-app/src/app/workspace/resource/representation/document/document.component.scss
apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.html
apps/dsp-app/src/app/workspace/resource/representation/text/text.component.html
apps/dsp-app/src/app/workspace/resource/representation/text/text.component.scss
apps/dsp-app/src/app/workspace/resource/representation/video/video.component.html
apps/dsp-app/src/styles/_elements.scss

style(mat-menu): apply black background to representation menu

---

apps/dsp-app/src/app/material-module.ts
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.html
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.scss
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.spec.ts
apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.html
apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.scss
apps/dsp-app/src/styles.scss
apps/dsp-app/src/styles/_elements.scss

chore: angular mdc migration slider

---

apps/dsp-app/src/app/main/guard/auth.guard.ts
apps/dsp-app/src/app/main/services/authentication.service.ts

fix(app): navigate to home after logout

---

apps/dsp-app/src/app/main/services/datadog-rum.service.ts

fix(type error): check existence of internal context

---

apps/dsp-app/src/app/project/ontology/ontology.service.ts

fix(type error): check existence of ReadOntology instances

---

apps/dsp-app/src/app/project/list/list-item-form/list-item-form.component.scss
apps/dsp-app/src/styles/_elements.scss

fix(action bubble position): reposition the action bubble

---

apps/dsp-app/src/app/user/membership/membership.component.scss

style(user membership): Clip long project names with overflow ellipsis

---

README.md
apps/dsp-app-e2e/project.json
apps/dsp-app/project.json
apps/dsp-app/src/app/workspace/results/list-view/resource-list/resource-list.component.html
apps/dsp-app/src/app/workspace/results/list-view/resource-list/resource-list.component.scss
apps/dsp-app/src/config/config.0845-test-server.json
apps/dsp-app/src/environments/environment.0845-test-server.ts
package.json

style(resource list): prevent shift/overlap of checkboxes

---

apps/dsp-app/src/app/workspace/results/list-view/resource-list/resource-list.component.html

fix(resource-list): remove erroneous text before each label

---

apps/dsp-app/src/app/workspace/resource/operations/add-value/add-value.component.html
apps/dsp-app/src/app/workspace/resource/operations/add-value/add-value.component.ts

fix(add-value): paragraph not showing as textarea

---

apps/dsp-app/src/styles/_elements.scss

style(representation components): set the text color of the menu items

---

apps/dsp-app/src/app/workspace/resource/directives/text-value-html-link.directive.ts

fix(text values): open all non internal links in a new tab

---

apps/dsp-app/src/app/workspace/resource/values/comment-form/comment-form.component.html

style(empty comment):  Keep empty comments placeholder unstyled

---

package-lock.json
package.json

chore: update js-lib to v8.3.1

---

apps/dsp-app/src/app/main/action/login-form/login-form.component.html
apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/resource-class-property-info.component.ts

fix(runtime errors): fix errors thrown

---

apps/dsp-app/src/app/main/header/header.component.ts
apps/dsp-app/src/app/project/list/list.component.ts
apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts
apps/dsp-app/src/app/system/users/users-list/users-list.component.ts
apps/dsp-app/src/app/workspace/resource/properties/properties.component.ts

resolves DEV-2542
Also:
- remove unnecessary subscription
- remove unnecessary refreshes when there are no changes

fix (type errors): fix type errors after dialog closed

---

apps/dsp-app/src/app/app-routing.module.ts
apps/dsp-app/src/app/main/dialog/dialog.component.html
apps/dsp-app/src/app/project/description/description.component.html
apps/dsp-app/src/app/project/description/description.component.spec.ts
apps/dsp-app/src/app/project/description/description.component.ts
apps/dsp-app/src/app/project/list/list.component.ts
apps/dsp-app/src/app/project/project-form/project-form.component.html
apps/dsp-app/src/app/project/project-form/project-form.component.scss
apps/dsp-app/src/app/project/project-form/project-form.component.spec.ts
apps/dsp-app/src/app/project/project-form/project-form.component.ts
apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.html
apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts
apps/dsp-app/src/app/system/projects/projects.component.ts
apps/dsp-app/src/app/user/overview/overview.component.html
apps/dsp-app/src/app/user/overview/overview.component.spec.ts
apps/dsp-app/src/app/user/overview/overview.component.ts
package.json

refactor(project edit dialog): remove dialog and replace in component

---

apps/dsp-app/src/app/workspace/resource/properties/properties.component.html
apps/dsp-app/src/app/workspace/resource/properties/properties.component.spec.ts
apps/dsp-app/src/app/workspace/resource/properties/properties.component.ts

fix(app): sort incoming links for more than 25

---

apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/resource-class-property-info.component.ts

fix(link to controlled vocabulary): Link to correct route

---

apps/dsp-app/src/app/workspace/resource/resource.component.ts

resolves DEV-2766 and DEV-2765

fix(resource): resources do not load from url

---

libs/vre/advanced-search/src/lib/data-access/advanced-search-service/advanced-search.service.ts
libs/vre/advanced-search/src/lib/data-access/gravsearch-service/gravsearch.service.ts

fix(gravsearch-service): incorrect gravsearch generated when searching for a linked property

---

apps/dsp-app/src/app/project/project.component.ts

fix(project): host listener triggers when user types in an input or textarea

---

libs/vre/shared/app-date-picker/src/lib/app-date-picker/app-date-picker.component.ts

fix(date-picker): fix YYYY-MM-dd formatting

---

apps/dsp-app/src/app/project/project.component.html
apps/dsp-app/src/app/project/project.component.ts

… to AvailableRoute and use the route constants value
resolves DEV-2872

fix(advanced search link): Add route constant

---

apps/dsp-app/src/app/app-routing.module.ts
apps/dsp-app/src/app/main/action/login-form/login-form.component.ts
apps/dsp-app/src/app/workspace/search/advanced-search/advanced-search-container.component.ts
libs/vre/shared/app-config/src/lib/app-config/app-constants.ts

refactor(routing): cleanup unused routes

---

libs/vre/advanced-search/src/lib/data-access/advanced-search-store/advanced-search-store.service.ts

feat(advanced-search): allow ordering by URI value

---

apps/dsp-app/src/app/project/description/description.component.ts

feat(project description): order project descriptions by language

---

apps/dsp-app/src/app/workspace/resource/resource.component.ts

fix(app/resource): removed developer feature that created annotation bug

---

apps/dsp-app/src/app/workspace/resource/representation/av-timeline/av-timeline.component.ts
apps/dsp-app/src/app/workspace/results/list-view/list-view.component.html

fix(type errors): fix type errors

---

apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.html
apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.scss
apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.ts

refactor(ontology-class-item): change how long labels are handled

---

apps/dsp-app/src/app/workspace/results/results.component.ts

fix(results): user unable to execute second fulltext search

---

apps/dsp-app/src/app/workspace/results/results.component.ts

fix(advanced-search): undefined error leads to blank page

---

apps/dsp-app/src/app/workspace/results/results.component.ts

fix(results): go back to search form button fix

---

libs/vre/shared/app-date-picker/src/lib/app-date-picker/app-date-picker.component.ts

fix(date-picker): date-picker doesn't show in advanced search

---

apps/dsp-app/src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts

resolves [DEV-2941](https://linear.app/dasch/issue/DEV-2941/edit-list-item-endless-loading-form)

fix(dsp-app): loading variable

---

apps/dsp-app/src/styles.scss

resolves DEV-3015 and DEV-3016

fix(dsp-app): prevent x overflow in dialog

---

apps/dsp-app/src/app/project/project-form/project-form.component.ts

fix(dsp-app): new projects have 20 characters shortcode

---

apps/dsp-app/src/app/main/guard/auth.guard.ts

fix: merge conflict

---

.prettierrc

Let's talk about those as it is a matter of preferences.

chore: add prettier general style

---

apps/dsp-app/src/app/user/user-form/password-form/password-form.component.ts
libs/vre/shared/app-helper-services/src/lib/project.service.ts
libs/vre/shared/app-session/src/lib/auth.service.ts

fix: various bugs

---

apps/dsp-app/src/app/main/guard/ontology-class-instance.guard.ts
apps/dsp-app/src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts

fix: ontology resource create and display

---

apps/dsp-app/src/app/project/project.component.html
apps/dsp-app/src/app/project/project.component.ts
libs/vre/shared/app-helper-services/src/lib/project.service.ts
libs/vre/shared/app-state/src/lib/projects/projects.state.ts

fix: Project Member cannot add instances of resources #DEV-3121

---

apps/dsp-app/src/app/workspace/resource/values/list-value/list-value.component.ts

fix: property value refresh #DEV-3106

---

apps/dsp-app/src/app/workspace/resource/values/geoname-value/geoname-value.component.ts

fix: geoname property lookup

---

apps/dsp-app/src/app/main/action/confirm-dialog/confirm-dialog.component.ts
apps/dsp-app/src/app/main/services/dialog.service.ts
apps/dsp-app/src/app/project/list/list-item-form/list-item-form.component.ts
apps/dsp-app/src/app/project/list/list.component.ts
apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts
apps/dsp-app/src/app/system/users/users-list/users-list.component.ts
apps/dsp-app/src/app/user/account/account.component.ts

Add confirm dialog service to make component code less verbose

refactor: add confirm dialog service

---

apps/dsp-app/src/app/main/services/component-communication-event.service.ts
apps/dsp-app/src/app/project/description/description.component.html
apps/dsp-app/src/app/project/description/description.component.ts
apps/dsp-app/src/app/workspace/resource/properties/properties.component.ts
apps/dsp-app/src/app/workspace/results/list-view/list-view.component.ts
libs/vre/shared/app-state/src/lib/projects/projects.state-model.ts
libs/vre/shared/app-state/src/lib/projects/projects.state.ts

repairs description component loading,
separates projects and membership loading, 
reloads resource list when resource is changed

fix(dsp-app): reloads resource list when resource is changed, separates projects and membership loading..

---

libs/vre/shared/app-session/src/lib/auth.service.ts
libs/vre/shared/app-state/src/lib/user/user.selectors.ts

fix: redirection to home issue when session is not valid

---

apps/dsp-app/src/app/workspace/resource/operations/add-value/add-value.component.ts

fix: adding new value for optional resource #DEV-3031

---

apps/dsp-app/src/app/user/user-form/user-form.component.ts

fix: bug when user change his language

---

apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.html
apps/dsp-app/src/app/user/user-form/user-form.component.html

resolves Flavies request on  DEV-3185

fix: no retry in edit user form

---

libs/vre/shared/app-state/src/lib/projects/projects.state.ts

fix(dsp-app): handles project edit errors (#DEV-3205)

---

apps/dsp-app/src/app/user/membership/membership.component.html
apps/dsp-app/src/app/user/membership/membership.component.ts

fix(dsp-app): manage user membership (#DEV-3218)

---

apps/dsp-app/src/app/main/directive/existing-name/existing-names.validator.ts
apps/dsp-app/src/app/project/ontology/resource-class-form/resource-class-form.component.ts

fix(dsp-app): resource class form validation (#DEV-3132)

---

apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.html
apps/dsp-app/src/app/workspace/resource/representation/audio/audio.component.ts

fix: audio slider moves on time change

---

apps/dsp-app/src/styles/_elements.scss

fix: flickering button

---

apps/dsp-app/src/app/project/create-project-form-page/create-project-form-page.component.ts
apps/dsp-app/src/app/project/reusable-project-form/reusable-project-form.component.ts
apps/dsp-app/src/app/project/reusable-project-form/shortcode-exists.validator.ts
libs/vre/shared/app-state/src/lib/projects/projects.selectors.ts

feat(project form): creating a new project with an existing short code (DEV-3204)

---

apps/dsp-app/src/app/workspace/resource/resource-link-form/resource-link-form.component.html
apps/dsp-app/src/app/workspace/resource/resource-link-form/resource-link-form.component.ts

fix(dsp-app): resource link form (#DEV-3203)

---

apps/dsp-app/src/app/workspace/results/list-view/list-view.component.html
apps/dsp-app/src/app/workspace/results/list-view/list-view.component.ts

fix(list-view): correct display logic

---

apps/dsp-app/src/app/project/create-project-form-page/create-project-form-page.component.ts

fix: cancel button in project form goes back to previous page

---

apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts

Fix deactivating as well as reactivating
resolves DEV-3206

fix(projects list): deactivating-a-project-not-possible (DEV-3206)

---

apps/dsp-app/src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts
apps/dsp-app/src/app/workspace/results/list-view/list-view.component.ts

fix: send gravsearch and search-count request simultaniously

---

apps/dsp-app/src/app/workspace/results/list-view/list-view.component.html

fix(dsp-app): fixes no search results section (DEV-3240)

---

libs/vre/shared/app-error-handler/src/lib/app-error-handler.ts

fix: display error on error handler

---

apps/dsp-app/src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts
apps/dsp-app/src/app/workspace/results/list-view/list-view.component.ts

fix(dsp-app): performs gravsearch count from advanced search

---

apps/dsp-app/src/app/workspace/resource/representation/representation.service.ts

fix: no bearer auth on iiif images

---

apps/dsp-app/src/app/workspace/results/list-view/list-view.component.html

fix: display resource permission warning message

---

apps/dsp-app/src/app/workspace/resource/resource-link-form/resource-link-form.component.ts

fix(dsp-app): resource link permissions (DEV-3252)

---

apps/dsp-app/src/app/project/list/list-item-element/list-item-element.component.ts
libs/vre/shared/app-string-literal/src/lib/multi-language-input.component.ts
libs/vre/shared/app-string-literal/src/lib/multi-language-textarea.component.ts

fix: list node gets updated

---

package-lock.json
package.json

chore: update dsp-js to v9.1.11

---

apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.scss
apps/dsp-app/src/styles/_elements.scss

fix(dsp-das): image viewer padding, arrows style. Resource list name css adjustments (DEV-3276)

---

apps/dsp-app/src/app/workspace/results/results.component.scss

fix:  search result list item style (DEV-3280)

---

apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts

fix: link to edit a project

---

apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.html
apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.scss

fix: slider is accessible

---

apps/dsp-app/src/app/project/list/list-item-form/list-item-form.component.ts

fix: new list node field error is not displayed

---

apps/dsp-app/src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts

fix: submit button on upload resource does not load indefinitely 

---

apps/dsp-app/src/app/workspace/resource/representation/add-region-form/add-region-form.component.ts
apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.ts

fix: image region  comment field  validation removed(DEV-3315)

---

apps/dsp-app/src/app/project/image-settings/image-settings.component.html
apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json

fix: image settings restriction note

---

apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.html
apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.ts
apps/dsp-app/src/app/project/collaboration/collaboration.component.html
apps/dsp-app/src/app/user/user-form/user-form.component.ts

fix: add user by project admin (DEV-3414)

---

apps/dsp-app/src/app/workspace/resource/values/list-value/list-value.component.ts

fix: resource item list value (DEV-3248)

---

apps/dsp-app/src/app/workspace/resource/properties/properties.component.html
apps/dsp-app/src/app/workspace/resource/properties/properties.component.ts

fix: resource attached project retrieving (#DEV-3424)

---

package-lock.json
package.json

chore: update dsp-js to v9.1.14

---

package-lock.json
package.json

chore: update dsp-js to v9.1.15

---

.github/workflows/main.yml
apps/dsp-app/cypress/e2e/system-admin/data-model-class.cy.ts

fix: data-model-class e2e (DEV-)

---

apps/dsp-app/src/app/workspace/resource/values/text-value/ck-editor.ts

fix: removed mergeTableCells functionality from CKEditor (#DEV-3473)

---

apps/dsp-app/src/app/workspace/resource/resource.component.ts
package.json

fix: filters out "has image file" property (DEV-3477)

---

apps/dsp-app/src/app/workspace/resource/resource.component.scss

fix: resource tooltip fit content (#DEV-3383)

---

apps/dsp-app/src/app/user/user-form/user-form.component.ts

fix(user form): set form to required (DEV-3527)

---

apps/dsp-app/src/app/workspace/resource/properties/resource-toolbar/resource-toolbar.ts
libs/vre/shared/app-error-handler/src/lib/app-error-handler.ts

fix: alerts user when a resource cannnot be erased

---

apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.html
apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.ts

fix: allows project admin to add members to the project (#DEV-3414)

---

apps/dsp-app/src/app/workspace/resource/resource.component.html

fix: resource label (#DEV-3550)

---

package-lock.json
package.json

chore: update dsp-js to v9.1.18

---

apps/dsp-app/src/app/system/users/users.component.html
apps/dsp-app/src/app/system/users/users.component.ts
libs/vre/shared/app-state/src/lib/user/user.selectors.ts
libs/vre/shared/app-state/src/lib/user/user.state-model.ts
libs/vre/shared/app-state/src/lib/user/user.state.ts

fix(loading state): use correct loading state

---

libs/vre/shared/app-state/src/lib/user/user.state.ts

fix(project members list): force reload project membership

---

libs/vre/shared/app-resource-properties/src/lib/existing-property-value.component.ts

fix(search results): use resources class instead of reading out url

---

apps/dsp-app/src/app/workspace/resource/resource.component.ts

fix(resource component): use getter

---

libs/vre/shared/app-resource-properties/src/lib/create-resource-form.component.ts
libs/vre/shared/app-resource-properties/src/lib/property-value.component.ts
libs/vre/shared/app-resource-properties/src/lib/resource-payloads-mapping.ts

fix: include a comment when creating a new value

---

apps/dsp-app/src/app/workspace/resource/properties/resource-toolbar/resource-toolbar.html

fix(menu): display only when an action is possible

---

libs/vre/shared/app-resource-properties/src/lib/switch-components/rich-text-switch.component.ts
libs/vre/shared/app-resource-properties/src/lib/switch-components/text-html-switch.component.ts

fix: standoff links are clickable

---

apps/dsp-app/src/app/workspace/resource/resource.component.html
libs/vre/shared/app-resource-properties/src/lib/property-value.component.ts
libs/vre/shared/app-state/src/lib/resource/resource.actions.ts
libs/vre/shared/app-state/src/lib/resource/resource.state.ts

fix(annotations): load the correct resource for annotations

---

apps/dsp-app/src/app/workspace/resource/resource.component.ts

fix: resource initialisation (DEV-3656)

---

apps/dsp-app/src/app/workspace/resource/resource.component.ts
libs/vre/shared/app-resource-properties/src/lib/edit-resource-label-dialog.component.ts

fix: resource is not reloaded after label update (#DEV-3607)

---

apps/dsp-app/src/app/system/projects/projects.component.ts

fix: reloads user projects after update (#DEV-3653)

---

apps/dsp-app/src/app/workspace/search/fulltext-search/fulltext-search.component.scss

fix: end full text search menu items with three dots instead of cropping (DEV-3648)

---

apps/dsp-app/src/app/workspace/resource/resource.component.ts

fix: title label update (DEV-3664)

---

libs/vre/shared/app-resource-properties/src/lib/resource-info-bar.component.ts

fix: project link (DEV-3666)

---

apps/dsp-app/src/app/app-routing.module.ts
apps/dsp-app/src/app/project/create-project-form-page/create-project-form-page.component.ts
apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts
apps/dsp-app/src/app/system/projects/projects.component.html
apps/dsp-app/src/app/system/projects/projects.component.ts
apps/dsp-app/src/app/user/user.component.html
libs/vre/shared/app-config/src/lib/app-config/app-constants.ts

feat: assigns new project to the current user automatically, if created from my projects (DEV-3658)

feat: assigns new project to the current user automatically, if creat…(DEV-3658)

---

libs/vre/shared/app-resource-page/src/lib/compound/compound.service.ts
libs/vre/shared/app-resource-page/src/lib/resource-tabs.component.ts

fix: refresh incoming resource (DEV-3676)

---

libs/vre/shared/app-state/src/lib/resource/resource.state.ts

fix: resource metadata are loaded

---

libs/vre/shared/app-representations/src/lib/region.service.ts
libs/vre/shared/app-resource-page/src/lib/resource-toolbar.component.ts

fix: highlights selected image region (#DEV-3700)

---

libs/vre/shared/app-resource-page/src/lib/resource-tabs.component.ts

fix: on resource change, display first tab

---

libs/vre/shared/app-resource-properties/src/lib/switch-components/list-switch.component.ts
libs/vre/shared/app-state/src/lib/projects/projects.selectors.ts

fix: property value add button permissions (#DEV-3723)

---

libs/vre/shared/app-resource-page/src/lib/resource-representation.component.ts

fix: resource switching

---

libs/vre/shared/app-helper-services/src/lib/project.service.ts
libs/vre/shared/app-representations/src/lib/resource-fetcher.service.ts
libs/vre/shared/app-resource-properties/src/lib/property-values.component.ts
libs/vre/shared/app-resource-properties/src/lib/switch-components/list-switch.component.ts
libs/vre/shared/app-state/src/index.ts
libs/vre/shared/app-state/src/lib/config.state.ts
libs/vre/shared/app-state/src/lib/projects/projects.selectors.ts
libs/vre/shared/app-state/src/lib/resource/resource.actions.ts
libs/vre/shared/app-state/src/lib/resource/resource.selectors.ts
libs/vre/shared/app-state/src/lib/resource/resource.state-model.ts
libs/vre/shared/app-state/src/lib/resource/resource.state.ts
libs/vre/shared/app-state/src/store.module.ts

fix: allows resource related project member or admin to edit its properties (DEV-3723)

---

libs/vre/advanced-search/src/lib/ui/property-form/property-form-link-value/property-form-link-value.component.html
libs/vre/advanced-search/src/lib/ui/property-form/property-form-link-value/property-form-link-value.component.scss
libs/vre/advanced-search/src/lib/ui/property-form/property-form-link-value/property-form-link-value.component.ts

fix: search autocomplete adjustments (DEV-3718)

---

apps/dsp-app/src/app/app.module.ts
apps/dsp-app/src/app/main/action/login-form/login-form.component.ts
apps/dsp-app/src/app/project/common-input/common-input.component.ts
apps/dsp-app/src/app/project/ontology/resource-class-form/resource-class-form.component.ts
apps/dsp-app/src/app/project/reusable-project-form/reusable-project-form.component.ts
apps/dsp-app/src/app/user/user-form/user-form.component.html
libs/vre/shared/app-property-form/src/lib/components/property-form.component.ts
libs/vre/shared/app-resource-properties/src/lib/create-resource-form.component.ts
libs/vre/shared/app-resource-properties/src/lib/edit-resource-label-dialog.component.ts
libs/vre/shared/app-resource-properties/src/lib/switch-components/interval-switch.component.ts
libs/vre/shared/app-resource-properties/src/lib/switch-components/text-switch.component.ts
libs/vre/shared/app-resource-properties/src/lib/switch-components/uri-switch.component.ts
libs/vre/shared/app-string-literal/src/lib/multi-language-input.component.ts

- common input now displays label on top with <mat-label>
- placeholder property is now called label

feat: add labels to every input

---

apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.html
apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.ts

fix: display ontology labels in prefffered language (DEV-3739)

---

libs/vre/shared/app-resource-properties/src/lib/property-values.component.ts

fix: property value gap adjustment (DEV-3718)

---

apps/dsp-app/src/app/workspace/resource/resource-link-form/resource-link-form.component.ts

fix: resource link form (DEV-3767)

---

libs/vre/shared/app-error-handler/src/lib/app-error-handler.ts

fix: change notification error message

---

libs/vre/shared/app-common/src/index.ts
libs/vre/shared/app-common/src/lib/resource.util.ts
libs/vre/shared/app-representations/src/lib/archive/archive.component.html
libs/vre/shared/app-representations/src/lib/archive/archive.component.ts
libs/vre/shared/app-representations/src/lib/audio/audio.component.html
libs/vre/shared/app-representations/src/lib/audio/audio.component.ts
libs/vre/shared/app-representations/src/lib/document/document.component.html
libs/vre/shared/app-representations/src/lib/document/document.component.ts
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.html
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts
libs/vre/shared/app-representations/src/lib/text/text.component.html
libs/vre/shared/app-representations/src/lib/text/text.component.ts
libs/vre/shared/app-representations/src/lib/video/video-more-button.component.ts
libs/vre/shared/app-resource-page/src/lib/resource-header.component.ts
libs/vre/shared/app-resource-page/src/lib/resource-toolbar.component.ts
libs/vre/shared/app-resource-properties/src/lib/property-value-action-bubble.component.ts

fix(resource permissions): check resource permissions for replacing files

---

apps/dsp-app/src/app/workspace/results/list-view/list-view.component.html
apps/dsp-app/src/app/workspace/results/list-view/resource-list/resource-list.component.html
apps/dsp-app/src/app/workspace/results/list-view/resource-list/resource-list.component.scss
apps/dsp-app/src/styles/_elements.scss

style(result list): make list items more responsive (DEV-3771)

---

libs/vre/shared/app-resource-page/src/lib/resource-tabs.component.ts
libs/vre/shared/app-resource-properties/src/lib/properties-display.component.ts

fix(properties): prevent toolbar buttons to trigger unnecessary requests

---

libs/vre/shared/app-resource-properties/src/lib/property-value.component.ts

fix: loader displayed on top when editing property values

---

libs/vre/shared/app-resource-page/src/lib/resource-tabs.component.ts

fix: tab do not change when a resource is reloaded

---

apps/dsp-app/src/app/main/directive/invalid-control-scroll.directive.ts

fix: prevents from scrolling exception (DEV-3774)

---

apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.html
apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts
apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json
libs/vre/shared/app-api/src/lib/services/admin/project-api.service.ts
libs/vre/shared/app-ui/src/lib/dialog/dialog.service.ts

feat: erase project + translations (DEV-3734)

---

apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.html
apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.scss
apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.ts
apps/dsp-app/src/app/project/collaboration/collaboration.component.html
apps/dsp-app/src/app/project/collaboration/collaboration.component.ts
apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json
libs/vre/shared/app-resource-properties/src/lib/value-components/nested-menu.component.ts

refactor(add user form): remove validation and error msgs

---

libs/vre/shared/app-common/src/lib/dsp-resource.ts
libs/vre/shared/app-resource-page/src/lib/compound/compound.service.ts
libs/vre/shared/app-resource-page/src/lib/resource-tabs.component.ts
libs/vre/shared/app-resource-page/src/lib/resource.component.ts

fix: editing a stillimage properties keep the same page active

---

apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-info-element.component.ts
apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/resource-class-property-info.component.ts

fix(cardinality change): include other properties, set the new cardinality

---

apps/dsp-app/src/app/system/projects/projects-list/erase-project-dialog/erase-project-dialog.component.ts

fix: erase project short code validation (DEV-3734)

---

apps/dsp-app/src/app/workspace/resource/directives/text-value-html-link.directive.ts

fix: opening Salsah links  (DEV-3830)

---

k6/justfile

chore(test): Use docker compose in justfile instead of deprecated docker-compose

---

libs/vre/shared/app-representations/src/lib/upload/upload-file.service.ts

fix: Url encode ingest upload url in order to support special characters in filenames (DEV-3865)

---

libs/vre/shared/app-representations/src/lib/resource-fetcher.service.ts
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.html
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts
libs/vre/shared/app-resource-page/src/lib/resource-fetcher.component.ts

fix: does not preserve image format on resource change (DEV-3834)

---

libs/vre/shared/app-state/src/lib/projects/projects.selectors.ts

fix: projectRestrictedViewSettings selector (DEV-3888)

---

libs/vre/shared/app-resource-page/src/lib/resource.component.ts

fix: compound object page reset when loading a new resource 

---

libs/vre/shared/app-resource-properties/src/lib/properties-display-incoming-link.service.ts
libs/vre/shared/app-resource-properties/src/lib/properties-display.component.ts
libs/vre/shared/app-ui/src/lib/pager/pager.component.html
libs/vre/shared/app-ui/src/lib/pager/pager.component.ts

feat: recursive incoming links loading (DEV-3792)

---

apps/dsp-app/src/app/workspace/results/list-view/list-view.component.ts
libs/vre/shared/app-resource-page/src/lib/resource-fetcher.component.ts
libs/vre/shared/app-resource-page/src/lib/resource-toolbar.component.ts

fix: in seach, reload the selected resource after editing

---

libs/vre/shared/app-resource-properties/src/lib/create-resource-dialog.component.ts
libs/vre/shared/app-resource-properties/src/lib/create-resource-form.component.ts
libs/vre/shared/app-resource-properties/src/lib/create-resource-page.component.ts
libs/vre/shared/app-resource-properties/src/lib/value-components/link-value.component.ts

fix: create resource issue (DEV-3913)

---

apps/dsp-app/src/app/project/collaboration/add-user/add-user.component.ts
apps/dsp-app/src/app/system/users/users-list/users-list.component.ts
apps/dsp-app/src/app/user/profile/profile.component.ts
libs/vre/shared/app-config/src/lib/app-config/dsp-dialog-config.ts

fix: side dialog position (DEV-3914)

---

libs/vre/shared/app-resource-properties/src/lib/create-resource-form.component.ts
libs/vre/shared/app-resource-properties/src/lib/property-value.component.ts

fix: prevents from saving empty property values (DEV-3919)

---

libs/vre/shared/app-resource-properties/src/lib/resource-payloads-mapping.ts

fix: removed decimal property default value (DEV-3923)

---

apps/dsp-app/src/app/user/create-user-page/create-user-dialog.component.ts

fix: create user as system administrator (DEV-3934)

---

libs/vre/shared/app-resource-properties/src/lib/create-resource-form.component.ts

fix: create resource with edited properties only (DEV-3937)

---

libs/vre/shared/app-resource-properties/src/lib/value-components/link-value.component.ts

fix: added linked resource autocomplete loading progress bar (DEV-3938)

---

libs/vre/shared/app-resource-properties/src/lib/value-components/list-value.component.ts

applies only for new (not yet stored) and non required values
resolves DEV-3941

fix(list property): introduce an empty option for new values

---

apps/dsp-app/cypress/e2e/system-admin/ontology.cy.ts

test: fix ontology creation

---

apps/dsp-app/cypress/e2e/system-admin/data-model-class.cy.ts
apps/dsp-app/cypress/e2e/system-admin/resource.cy.ts
apps/dsp-app/cypress/support/pages/add-resource-instance-page.ts
libs/vre/shared/app-resource-properties/src/lib/property-value-switcher.component.ts

test: reimplement tests

---

apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/cardinality-component/cardinality.component.ts
apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/resource-class-property-info.component.html

fix(cardinality toggles): disable if not project or sys admin

---

libs/vre/shared/app-property-form/src/lib/components/create-property-form-dialog.component.ts
libs/vre/shared/app-property-form/src/lib/components/property-form.component.ts

fix: create new property type (DEV-4008)

---

libs/vre/shared/app-list/src/lib/list-item-form/edit-list-item/create-list-item-dialog.component.ts

fix: allows to add list item without comments (DEV-4016)

---

apps/dsp-app/src/app/project/collaboration/select-group/select-group.component.html
apps/dsp-app/src/app/project/collaboration/select-group/select-group.component.ts
apps/dsp-app/src/app/system/users/users-list/users-list.component.ts

fix(update group membership): trigger update after each change (DEV-3857)

---

apps/dsp-app/src/index.html

feat: transparent status bar

---

libs/vre/shared/app-representations/src/lib/add-region-form/add-region-form.component.ts
package-lock.json

fix: a comment on a created region is of type: rich text

---

libs/vre/shared/app-representations/src/lib/video/video.component.html
libs/vre/shared/app-representations/src/lib/video/video.component.ts
libs/vre/shared/app-resource-page/src/lib/resource-fetcher.component.ts

fix: segments are displayed correctly when the video is changed

---

libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts

fix: use correct property(DEV-4056)

---

libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts

fix: refresh still image after replacing file

---

apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.ts

fix: updates class list labels on language change (DEV-4052)

---

libs/vre/shared/app-common-to-move/src/lib/dialog/dialog.component.html
libs/vre/shared/app-representations/src/lib/replace-file-form/replace-file-form.component.html
libs/vre/shared/app-representations/src/lib/replace-file-form/replace-file-form.component.ts
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts
libs/vre/shared/app-representations/src/lib/upload/upload.component.ts

fix: pass projectUuid via input (DEV-4055)

---

apps/dsp-app/src/app/project/common-input/common-input.component.ts
apps/dsp-app/src/app/project/ontology/resource-class-form/resource-class-form.component.ts
apps/dsp-app/src/app/project/reusable-project-form/reusable-project-form.component.ts
libs/vre/shared/app-property-form/src/lib/components/property-form.component.ts
libs/vre/shared/app-representations/src/lib/add-region-form/add-region-form.component.ts
libs/vre/shared/app-segment-support/src/lib/create-segment-dialog.component.ts

fix: display asterisks for marking a field as required (DEV-4053)

---

libs/vre/shared/app-representations/src/lib/third-party-iiif/third-party-iiif.ts

fix(iiif url validation): add support for V1 (DEV-4074)

---

libs/vre/shared/app-representations/src/lib/third-party-iiif/iiif-url-validator.ts
libs/vre/shared/app-representations/src/lib/third-party-iiif/third-party-iiif.component.ts

feat(iiif validation): fetch retry without HEAD (DEV-4075)

---

apps/dsp-app/src/app/project/common-input/common-input.component.ts

fix: add missing brackets (DEV-4069)

---

apps/dsp-app/src/app/workspace/resource/resource-link-form/resource-link-form.component.html

fix: allows sysadmin to create link object from search (DEV-4054)

---

k6/justfile
k6/pages/home-page.js
k6/pages/resource-page.js
k6/pages/single-resource-page.js
k6/tests/first-page-load.js
k6/tests/load-resource.js
k6/tests/load-single-resource.js

- **Update existing test, use k6chaijs for assertions**
- **add just clean**
- **add run-all to justfile**
resolves DEV-

refactor: Use k6chaijs for assertions

---

nx.json

chore: use local nx runner

---

libs/vre/shared/app-resource-properties/src/lib/property-value.component.scss
libs/vre/shared/app-resource-properties/src/lib/property-value.component.ts

fix: sentry typeerror: cannot read properties of undefined reading

---

libs/vre/advanced-search/src/lib/data-access/gravsearch-service/gravsearch.service.ts

fix: gravSearch does not equal operator for list value (DEV-4097)

---

libs/vre/shared/app-resource-properties/src/lib/value-components/geoname-value.component.ts

fix: geoname displayName exception (DEV-4105)

---

libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts

fix: prevents from throwing viewer exceptions (DEV-4083)

---

libs/vre/shared/app-error-handler/src/lib/app-error-handler.ts
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.html
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts

fix: disables download button, if resource is not loaded (DEV-4020)

---

apps/dsp-app/cypress/e2e/system-admin/data-model-class.cy.ts
libs/vre/shared/app-ontology/src/lib/resource-class-info/resource-class-info.component.html

test: a user should be able to delete a data model class(e2e)

---

libs/vre/shared/app-resource-properties/src/lib/properties-display.component.ts

fix: display condition of outgoing standoff links  (DEV-4032)

---

libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts

fix: restored image format change (DEV-4143)

---

libs/vre/shared/app-representations/src/lib/document/document.component.ts

fix: updates parent resource after replacing resource file (DEV-4172)

---

libs/vre/shared/app-resource-properties/src/lib/upload2.component.ts

fix: add support for uppercase file extensions (DEV-4148)

---

libs/vre/shared/app-ontology-classes/src/lib/ontology-class-instance/ontology-class-instance.component.ts

feat: order resource list by label (DEV-4164)

---

.github/workflows/main.yml

chore: add Google space notifications

---

apps/dsp-app/cypress/e2e/system-admin/file-representation.cy.ts
libs/vre/shared/app-representations/src/lib/third-party-iiif/third-party-iiif.component.ts
libs/vre/shared/app-representations/src/lib/third-party-iiif/third-party-iiif.ts

feat: accept encoded segments for region, size and rotation (DEV-4140)

---

libs/vre/shared/app-common-to-move/src/lib/status/status.component.ts
libs/vre/shared/app-common/src/lib/dsp-resource.ts
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.html
libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts
libs/vre/shared/app-resource-page/src/lib/compound/compound-arrow-navigation.component.ts
libs/vre/shared/app-resource-page/src/lib/compound/compound-navigation.component.ts
libs/vre/shared/app-resource-page/src/lib/compound/compound-viewer.component.ts
libs/vre/shared/app-resource-page/src/lib/compound/compound.service.ts

fix: shows 403 status error when incoming resource representation cannot be loaded due to lack of permissions (DEV-4146)

---

libs/vre/shared/app-property-form/src/lib/components/property-form.component.ts

fix: sets property form default language  (DEV-4182)

---

apps/dsp-app/cypress/e2e/logged-out-user/data-model-class.cy.ts

test: a non authorized user cannot access the data model class

---

libs/vre/shared/app-representations/src/lib/third-party-iiif/third-party-iiif.component.html
libs/vre/shared/app-representations/src/lib/third-party-iiif/third-party-iiif.component.ts

fix: initialise with empty function, call onChange also if invalid

---

libs/vre/shared/app-resource-properties/src/lib/upload.component.ts

I uploaded one file locally, it worked.

feat: Allow JSON files as text files (DEV-4222)

---

libs/vre/shared/app-list/src/lib/list-page.component.ts

fix: open as side dialog (DEV-4226)

---

apps/dsp-app/cypress/e2e/system-admin/file-representation.cy.ts

test: remove unreliable parts (DEV-4272)

---

libs/vre/shared/app-list/src/lib/list-item/list-item.component.ts

fix: display form only for admins (DEV-4185)

---

libs/vre/shared/app-ontology/src/lib/property-info/property-info.component.ts

fix: collect classes of all ontologies using a property (DEV-4240)

---

package-lock.json
package.json

refactor: bump js lib version (4269)

---

libs/vre/shared/app-ontology/src/lib/ontology.component.ts

fix: display class name (DEV-4214)

---

libs/vre/shared/app-representations/src/lib/still-image/still-image-toolbar.component.ts

fix: remove button width

---

apps/dsp-app/cypress/e2e/project-member/resource-project-admin.cy.ts

test(e2e): disable failing admin project resource tests (DEV-2380)

---

libs/vre/shared/app-representations/src/lib/still-image/still-image-toolbar.component.html

fix: reset zoom (DEV-4376)

---

.github/dependabot.yml

closes https://github.com/dasch-swiss/dsp-das/pull/1925

chore: add ckeditor5-custom-build to dependabot ignored list

---

libs/vre/resource-editor/resource-properties/src/lib/property-value-switcher.component.ts

fix: get the template on changes (DEV-4228)

---

libs/vre/shared/app-list/src/lib/list-item-form/reusable-list-item-form.component.ts

fix: reusable list item form validation (DEV-4374)

---

libs/vre/shared/app-help-page/src/lib/footer/footer.component.html

chore: update DaSCH address (DEV-4440)

---

.github/dependabot.yml

chore: decrease Dependabot PRs number and interval

---

libs/vre/shared/app-ontology/src/lib/resource-class-info/resource-class-info-element.component.ts

fix: make ontology class list numbers smaller (DEV -4444)

---

libs/vre/resource-editor/resource-properties/src/lib/property-row.component.scss
libs/vre/resource-editor/resource-properties/src/lib/property-row.component.ts

fix: each haslinktoclass property is displayed as linked resource

---

.github/dependabot.yml

chore: add more specific rule for @angular-devkit

---

libs/vre/resource-editor/representations/src/lib/archive/archive.component.ts

fix: detect changes in Archive Component

---

apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json
apps/dsp-app/src/assets/i18n/fr.json
apps/dsp-app/src/assets/i18n/it.json
apps/dsp-app/src/assets/i18n/rm.json
libs/vre/ui/ui/src/lib/pager/pager.component.html
libs/vre/ui/ui/src/lib/pager/pager.component.scss

new style, overviewed with Daniela :

fix: update paginator style

---

libs/vre/resource-editor/resource-properties/src/lib/properties-display.component.ts

fix: standoff links work again

---

libs/vre/resource-editor/representations/src/lib/still-image/osd-drawer.service.ts
libs/vre/resource-editor/resource-editor/src/lib/annotation-tab.component.ts

fix: jumps to selected annotation region (DEV-4542)

---

apps/dsp-app/cypress/e2e/system-admin/resource.cy.ts

test: skip footnote test

---

libs/vre/resource-editor/representations/src/lib/still-image/osd-drawer.service.ts
libs/vre/resource-editor/resource-editor/src/lib/annotation-tab.component.ts

https://dasch.sentry.io/issues/6269606463/?environment=prod&project=4506122171252736&query=release%3A11.25.0&referrer=release-issue-stream

fix: selected region click only fires when a region iri is found

---

libs/vre/3rd-party-services/analytics/project.json
libs/vre/3rd-party-services/api/project.json
libs/vre/core/config/project.json
libs/vre/core/error-handler/project.json
libs/vre/core/session/project.json
libs/vre/core/state/project.json
libs/vre/pages/ontology/list/project.json
libs/vre/pages/ontology/ontology-classes/project.json
libs/vre/pages/ontology/ontology/project.json
libs/vre/pages/project/project/project.json
libs/vre/pages/search/advanced-search/project.json
libs/vre/pages/search/search/project.json
libs/vre/pages/system/system/project.json
libs/vre/pages/user-settings/settings/project.json
libs/vre/pages/user-settings/user/project.json
libs/vre/resource-editor/property-form/project.json
libs/vre/ui/date-picker/project.json
libs/vre/ui/notification/project.json
libs/vre/ui/progress-indicator/project.json
libs/vre/ui/string-literal/project.json
libs/vre/ui/ui/project.json

this command allows to list the ts errors in the current project

chore: add tsc command to nx projects

---

apps/dsp-app/cypress/e2e/system-admin/resource.cy.ts

test: remove not reliable footnote test

---

libs/vre/pages/project/project/src/lib/project/project.component.ts
libs/vre/resource-editor/resource-properties/src/lib/incoming-links-property.component.ts

fix: incoming links update properly

---

libs/vre/ui/ui/src/lib/pipes/add-target-blank.pipe.ts

fix: can navigate to internal links

---

.github/dependabot.yml

chore: add entries to Dependabot file

---

libs/vre/resource-editor/resource-editor/src/lib/annotation-toolbar.component.ts

fix: pass viewContainerRef (DEV-4671)

---

apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json
apps/dsp-app/src/assets/i18n/fr.json
apps/dsp-app/src/assets/i18n/it.json
apps/dsp-app/src/assets/i18n/rm.json
libs/vre/pages/project/project/src/lib/edit-project-form-page.component.ts

fix: bring back, fix and improve some translations (DEV-4676)

---

libs/vre/ui/ui/src/lib/ck-editor/ck-editor.ts

fix: incoming links not working properly when creating a new one

---

apps/dsp-app/src/styles/_elements.scss
libs/vre/resource-editor/properties-display/src/lib/incoming-standoff-link-value.component.ts
libs/vre/resource-editor/properties-display/src/lib/properties-display.component.ts
libs/vre/resource-editor/resource-properties/src/index.ts
libs/vre/resource-editor/resource-properties/src/lib/create-resource-form.component.ts
libs/vre/resource-editor/resource-properties/src/lib/property-row.component.scss
libs/vre/resource-editor/resource-properties/src/lib/property-row.component.ts
libs/vre/resource-editor/resource-properties/src/lib/property-value-action-bubble.component.scss
libs/vre/resource-editor/resource-properties/src/lib/property-value.component.scss
libs/vre/resource-editor/resource-properties/src/lib/property-value.component.ts
libs/vre/resource-editor/resource-properties/src/lib/switch-components/rich-text-switch.component.ts
libs/vre/resource-editor/resource-properties/src/lib/viewer-components/rich-text-viewer.component.ts
libs/vre/resource-editor/resource-properties/src/resource-properties.components.ts

refactor: improve row styling of resource editor

---

apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json

fix: translations (DEV-4726)

---

libs/vre/resource-editor/representations/src/lib/audio/audio-toolbar.component.ts
libs/vre/resource-editor/representations/src/lib/video/video-toolbar.component.ts

fix: register custom icon

---

libs/vre/resource-editor/resource-properties/src/lib/existing-property-value.component.ts
libs/vre/resource-editor/resource-properties/src/lib/property-row.component.ts
libs/vre/resource-editor/resource-properties/src/lib/viewer-components/rich-text-viewer.component.ts

fix: footnotes display works again

---

libs/vre/pages/project/project/src/lib/project/project.component.scss

fix: side nav css (DEV-4725)

---

.github/workflows/main.yml

chore: update the rule when PRs should be triggered

---

libs/vre/resource-editor/representations/src/lib/still-image/still-image-toolbar.component.html

fix: bool expression (DEV-4826)

---

libs/vre/resource-editor/resource-properties/src/lib/viewer-components/rich-text-viewer.component.ts

feat: break texts

---

libs/vre/resource-editor/representations/src/lib/region.service.ts
libs/vre/shared/app-common-to-move/src/lib/incoming.service.ts
package-lock.json
package.json

refactor: replace getIncomingRegions with dedicated endpoint (DEV-4824) 

---

apps/dsp-app/src/styles/_elements.scss

fix: no results css (DEV-4802)

---

libs/vre/resource-editor/properties-display/src/lib/properties-display.component.ts

fix: resource-editor property title does not overlap with buttons

---

libs/vre/resource-editor/representations/src/lib/still-image/still-image-toolbar.component.html
libs/vre/resource-editor/representations/src/lib/still-image/still-image-toolbar.component.ts

style: align items vertically

---

libs/vre/resource-editor/resource-editor/src/lib/licenses-logo-mapping.ts

feat: add new licenses logo for CC0 and CC PDM 1.0

---

apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json
apps/dsp-app/src/assets/i18n/fr.json
apps/dsp-app/src/assets/i18n/it.json
libs/vre/resource-editor/resource-editor/src/lib/resource-fetcher.component.ts

fix: resource editor displays a message when resource access is unauthorized

---

docs/user-guide/project.md
libs/vre/resource-editor/resource-properties/src/lib/upload.component.ts

feat: add EPUB, HTM abd HTML filetypes support (DEV-5081)

---

libs/vre/resource-editor/resource-properties/src/lib/resource-payloads-mapping.ts
libs/vre/resource-editor/resource-properties/src/lib/switch-components/time-switch.component.ts
libs/vre/resource-editor/resource-properties/src/lib/value-components/time-value.component.ts

fix: Do not preset the time field (DEV-5004)

---

libs/vre/resource-editor/property-form/src/lib/components/property-form.component.ts
libs/vre/shared/app-helper-services/src/lib/ontology.service.ts

fix: unsupported link to Representation subclasses is displayed as link property; disable editing of uneditable fields (DEV-5086)

---

apps/dsp-app/src/assets/i18n/de.json
apps/dsp-app/src/assets/i18n/en.json
apps/dsp-app/src/assets/i18n/fr.json
apps/dsp-app/src/assets/i18n/it.json
libs/vre/resource-editor/resource-properties/src/lib/resource-form-legal.component.ts

feat: rename license labels

---

libs/vre/pages/ontology/ontology/src/lib/resource-classes/resource-class-info/cardinality-component/cardinality.component.ts

feat: disable multiple checkbox for boolean object type (DEV-5221)

---

libs/vre/pages/user-settings/user/src/lib/project-overview/project-card.component.ts

fix: set min-size for preventing shift (DEV-5327)

---

libs/vre/3rd-party-services/open-api/dsp-api_spec.yaml
libs/vre/ui/date-picker/src/lib/app-date-picker/app-date-picker.component.html

fix: track by unique (DEV-5420)

---

.github/dependabot.yml
CLAUDE.md

chore: NGXS leftovers cleanup

---

apps/dsp-app/src/styles.scss
apps/dsp-app/src/styles/_mixins.scss
apps/dsp-app/src/styles/_responsive.scss
apps/dsp-app/src/styles/_search.scss
libs/vre/pages/project/project/src/lib/description/project-description-page.component.scss
libs/vre/pages/project/project/src/lib/project-settings/collaboration/add-user/add-user.component.scss
libs/vre/pages/project/project/src/lib/project-settings/collaboration/collaboration-page.component.scss
libs/vre/pages/search/search/src/lib/fulltext-search/fulltext-search.component.scss
libs/vre/pages/search/search/src/lib/search-panel/search-panel.component.scss
libs/vre/pages/system/system/src/lib/projects/projects-list/projects-list.component.scss
libs/vre/pages/system/system/src/lib/system-page.component.scss
libs/vre/pages/user-settings/user/src/lib/account/account.component.scss
libs/vre/pages/user-settings/user/src/lib/user-menu/user-menu.component.scss
libs/vre/pages/user-settings/user/src/lib/user.component.scss
libs/vre/shared/app-common-to-move/src/lib/status/status.component.scss
libs/vre/shared/app-help-page/src/lib/grid/grid.component.scss

chore(Saas Dart): Migrate imports and global built-in functions (DEV-5445)

---

libs/vre/resource-editor/resource-editor/src/lib/incoming-resource-header.component.ts
libs/vre/resource-editor/resource-editor/src/lib/resource-edit-more-menu/resource-edit-more-menu.component.ts
libs/vre/resource-editor/resource-editor/src/lib/resource-toolbar.component.ts

fix: reintroduce edit label for pages (DEV-5468)
