dasch-swiss/dsp-das

yarn.lock
Upgrade querystringify to version 2.0.0 or later. For example:
```
querystringify@^2.0.0:
version "2.0.0"
=> fix: Vulnerability issue "querystringify"

src/app/app-global.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/main/footer/footer.component.html, src/app/main/footer/footer.component.scss, src/app/main/footer/footer.component.spec.ts, src/app/main/footer/footer.component.ts, src/app/main/grid/grid.component.html, src/app/main/grid/grid.component.scss, src/app/main/grid/grid.component.ts, src/app/main/header/header.component.html, src/app/main/help/help.component.html, src/app/main/help/help.component.scss, src/app/main/help/help.component.spec.ts, src/app/main/help/help.component.ts, src/app/main/info-menu/info-menu.component.html, src/app/main/info-menu/info-menu.component.scss, src/app/main/info-menu/info-menu.component.spec.ts, src/app/main/info-menu/info-menu.component.ts, src/app/main/main.component.html, src/app/main/main.component.scss, src/app/main/main.component.spec.ts, src/app/main/main.component.ts
Resolves #82 and closes #81 
Moved the status/info menu to an own page including links to user-guide documentation, links to github development / release notes and links to dasch.swiss and discuss / forum page.
Separate footer which can be used on the main landing page and on this new help page
=> Help / info page

package.json, yarn.lock
closes #248 
this branch has been tested with knora-api v12.0.0 and [knora-ui modules - branch wip/upgrade-knora-api-js-lib](https://github.com/dasch-swiss/knora-ui/pull/404)
=> Upgrade knora-api-js-lib to v0.2.0

src/app/main/dialog/dialog.component.html, src/app/project/list/list-info-form/list-info-form.component.html, src/app/project/list/list-info-form/list-info-form.component.ts, src/app/project/ontology/source-type-form/source-type-form.component.html, src/app/project/ontology/source-type-form/source-type-form.component.ts, src/app/project/project-form/project-form.component.html, src/app/project/project-form/project-form.component.ts, src/app/user/user-form/password-form/password-form.component.html, src/app/user/user-form/user-form.component.html, src/app/user/user-form/user-form.component.ts
In this PR I replaced the reset buttons in forms like:
- project-form
- user-form
- list-form
We had some issues with the reset button in combination with stringLiteralInput and list of keywords. So, I replaced reset with cancel which closes the dialog box without doing anything on the form data. I kept the method `reset()` to go back to reset-button and to fix the issues we had. But at the moment I do not have time to fix it. We can discuss if we should get rid of the reset functionality completely... In this case I will try to refactor the relevant forms
=> Replace reset buttons with cancel button

CHANGELOG.md, Dockerfile, Makefile, package-lock.json, package.json
This PR resolves the publish issue we had with docker configuration. It's needed for our first prerelease of the app: v3.0.0-rc.0
=> Fix: Update docker environment

src/app/main/footer/footer.component.html, src/app/main/main.component.html
resolves [DSP-295](https://dasch.myjetbrains.com/youtrack/issue/DSP-295)
=> DSP-295 Open external link in new tab

src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts
resolves [DSP-700](https://dasch.myjetbrains.com/youtrack/issue/DSP-700)
=> DSP-700 Fix broken link to project

src/app/main/header/header.component.html, src/app/main/header/header.component.spec.ts
resolves [DSP-674](https://dasch.myjetbrains.com/youtrack/issue/DSP-674)
As long we do not use the full dsp-ui search panel, which comes with advanced and expert search included, we can use only the fulltext-search-panel. 
The real bug will be solved in dsp-ui-lib.
=> DSP-674 Replace search-panel with fulltext-search

src/app/main/dialog/dialog.component.html, src/app/main/header/header.component.html, src/app/main/header/header.component.ts, src/assets/i18n/en.json, src/assets/style/_elements.scss
resolves [DSP-850](https://dasch.myjetbrains.com/youtrack/issue/DSP-850)
=> DSP-850 Navigation and dialog box to create a new resource

src/app/main/dialog/dialog.component.html, src/app/main/dialog/dialog.component.scss, src/app/main/dialog/dialog.component.ts, src/app/project/ontology/default-data/default-resource-classes.ts, src/app/project/ontology/ontology.component.html, src/app/project/ontology/ontology.component.ts, src/app/project/ontology/resource-class-form/resource-class-form.component.ts
resolves DSP-860
In this PR I reactivated the "Create resource class" and "Delete resource class". "Create" and "Add" properties to resource class is part of another user story (DSP-861 and DSP-862) and will be done in next PR.
For the reviewers: You can try to add resource class to the ontology with following steps:
- Login as system admin or as project admin
- Go to project page. In case you're logged-in as project admin, open the corresponding project.
- Open tab "Data model"
- Select ontology (in case the project has more than 1 ontology)
- Click on "Create resource class" and select the resource type you want to add
- A dialog box opens and you have to enter a resource class name and description
- Click on next and just fill in first input field of first property e.g. "Title" --> …
=> DSP-860: Ontology editor: Create resource class

.github/pull_request_template.md, .github/workflows/main.yml
resolves DSP-920
- Default branch is already set to "main" branch
&rarr; <https://github.com/dasch-swiss/dsp-app/settings/branches>
- Branch protections rule is set to "main" branch too
&rarr; <https://github.com/dasch-swiss/dsp-app/settings/branches>
- The base branch of all open PRs is already set to "main" branch
=> DSP-920 Renaming default github branch to "main"

src/app/main/header/header.component.html
=> DSP-1085 Hide link to the resource form in the header when logged out

src/app/main/header/header.component.ts, src/app/project/board/board.component.ts, src/app/project/collaboration/add-user/add-user.component.ts, src/app/project/list/list.component.ts, src/app/project/ontology/ontology.component.ts, src/app/system/projects/projects-list/projects-list.component.ts, src/app/system/projects/projects.component.ts, src/app/system/users/users-list/users-list.component.ts, src/app/user/account/account.component.ts, src/app/user/profile/profile.component.ts
=> fix(dialog): Fixed dialog box height issue (DSP-1211)

src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
=> feat(select-resource-class): allow accented character (DSP-1241)

README.md, src/app/app-global.ts, src/app/app-routing.module.ts, src/app/main/header/header.component.html
=> refactor(app+main)!: comment out the search and everything related to resources (DSP-1291)

src/app/app-routing.module.ts, src/app/main/login/login.component.html, src/app/main/login/login.component.ts
=> refactor!: set up the login page as a starting page (DSP-1292)

src/app/app-routing.module.ts, src/app/main/login/login.component.html, src/app/main/login/login.component.ts, src/app/main/main.component.spec.ts, src/app/main/main.component.ts
=> fix(routing): bring back the route handler in main component (DSP-1303)

package-lock.json, src/app/main/dialog/dialog.component.html, src/app/project/ontology/ontology.component.html, src/app/project/ontology/ontology.component.ts, src/app/project/ontology/resource-class-form/resource-class-form.component.html, src/app/project/ontology/resource-class-form/resource-class-form.component.ts
=> feat(ontology): edit res class info (DSP-1209)

src/app/project/list/list.component.html, src/app/project/list/list.component.scss, src/app/project/list/list.component.spec.ts, src/app/project/list/list.component.ts
=> feat(list-editor): delete list root node (DSP-1356)

src/app/app-routing.module.ts, src/app/project/ontology/ontology.component.html, src/app/project/ontology/ontology.component.scss, src/app/project/ontology/ontology.component.ts, src/app/project/ontology/property-info/property-info.component.html, src/app/project/ontology/property-info/property-info.component.scss, src/app/project/ontology/property-info/property-info.component.ts
resolves DSP-1364
This is a first version of a separate list of properties. In another task we will add a filter and sort button.
=> feat(ontology): separate list of ontology properties (DSP-1364)

.github/workflows/main.yml, e2e/src/footer.e2e-spec.ts, find-ignored-tests.sh
This PR adds a script to the app that finds ignored tests. At the moment it's prepared to find only `fdescribe` and `fit` in tests. `xdescribe` and `xit` are commented out because of the ignored VRE part of the app. 
The script runs in github actions (CI) workflow.
=> chore(tests): script to find ignored tests

package-lock.json, package.json, src/app/main/dialog/dialog.component.html, src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.html, src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts, src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts, src/app/project/list/list-item-form/list-item-form.component.html, src/app/project/list/list-item-form/list-item-form.component.ts, src/app/project/list/list-item/list-item.component.html, src/app/project/list/list-item/list-item.component.spec.ts, src/app/project/list/list-item/list-item.component.ts, src/app/project/list/list.component.ts
=> feat(list-editor): insert a child node at a specific position (DSP-1301)

src/app/project/board/board.component.ts
=> refactor(project metadata page): enable error handler (DSP-1396)

src/app/system/users/users-list/users-list.component.ts
=> fix(users): update session the correct way (DSP-690)

src/app/project/board/board.component.ts, src/app/project/collaboration/collaboration.component.ts, src/app/project/list/list.component.spec.ts, src/app/project/list/list.component.ts, src/app/project/ontology/ontology.component.ts, src/app/project/permission/permission.component.ts, src/app/project/project.component.html, src/app/project/project.component.ts, src/app/system/users/users-list/users-list.component.ts
=> feat(project): better error handler in case a project does not exist (DSP-1401)

angular.json, package.json, src/config/config.test-server.json, src/environments/environment.test-server.ts
resolves DSP-1650
* you can run the app with `ng s --configuration=test-server` or with `npm run start-with-test-server`
* open (for example) the following URL to see if you have the book resource with all the images: <http://localhost:4200/resource/http:%2F%2Frdfh.ch%2F0803%2Fc5058f3a>
=> chore(environment): add test-server config (DSP-1650)

src/app/project/collaboration/add-user/add-user.component.ts, src/app/project/project-form/project-form.component.ts
=> chore(project): resolve regex term (DSP-1654)

src/app/workspace/resource/resource-properties/resource-properties.component.ts
=> fix(resource): add if condition (DSP-1655)

README.md, docs/how-to-contribute/index.md
=> docs: update documentation about contribution (DSP-1657)

src/app/material-module.ts, src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.scss, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.scss, src/app/workspace/resource/resource.component.ts
=> feat(resource): display region annotations in still images (DSP-1585)

src/app/workspace/results/results.component.html, src/app/workspace/results/results.component.scss, src/app/workspace/results/results.component.ts
resolves DSP-1575
@flavens When page is refreshed with search string in the url, it displays search results on the page but same search string is not displayed in the search input box.
This bug requires changes in dsp-ui-lib and can be fixed in separate PR.
=> fix: disable progress bar if search results are empty (DSP-1575)

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts, src/app/main/cookie-policy/cookie-policy.component.scss, src/app/main/main.component.html, src/app/main/main.component.scss, src/app/main/main.component.ts
=> chore(cookie-policy): reactivate the cookie policy banner (DSP-1727)

src/app/main/main.component.scss, src/app/main/main.component.ts
=> chore: empty landing page instead login (DSP-1756)

README.md, src/app/main/help/help.component.ts
I thought the case-sensitivity in a URL doesn't matter. I was wrong. The links to the <https://docs.dasch.swiss/DSP-APP> were broken because <https://docs.dasch.swiss/dsp-app> does not work.
=> chore: fix dead links to the documentation

docs/user-guide/project.md, src/app/project/ontology/ontology-form/ontology-form.component.html, src/app/project/ontology/ontology-form/ontology-form.component.ts, src/assets/style/_elements.scss
=> docs(ontology): update docs and show hint in ontology-form (DSP-1139)

package-lock.json, src/app/project/ontology/default-data/default-properties.ts, src/app/project/ontology/ontology.component.html, src/app/project/ontology/property-form/property-form.component.spec.ts, src/app/project/ontology/resource-class-info/resource-class-info.component.html
=> feat(ontology): display description for default and existing props (DSP-1154)

src/app/main/dialog/dialog.component.html, src/app/main/dialog/dialog.component.ts, src/app/project/ontology/property-form/property-form.component.spec.ts, src/app/project/ontology/property-form/property-form.component.ts, src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts, src/app/project/ontology/resource-class-info/resource-class-info.component.ts
=> feat(ontology): add property to res class that is in use (DSP-1631)

package-lock.json, package.json, src/app/app.module.ts, src/app/main/pipes/split.pipe.spec.ts, src/app/main/pipes/split.pipe.ts, src/app/workspace/resource/representation/upload/upload.component.html, src/app/workspace/resource/representation/upload/upload.component.scss, src/app/workspace/resource/representation/upload/upload.component.spec.ts, src/app/workspace/resource/representation/upload/upload.component.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
=> feat(resource): upload pdf document (DSP-1776)

src/app/project/ontology/ontology-form/ontology-form.component.html, src/app/project/ontology/ontology-form/ontology-form.component.spec.ts, src/app/project/ontology/ontology-form/ontology-form.component.ts
resolves DSP-1139
We had an issue in the "create ontology" form. The regex didn't work as expected. As the DSP-API documentation says: "An ontology name must be a valid XML NCName. [...] A user-created ontology name may not start with the letter v followed by a digit". Special characters (incl. Umlauts etc), spaces and leading numbers are not allowed.
In this PR I fixed the regex and turned off the autocomplete (because it hides the error message below the field).
=> fix(ontology): fix regex pattern in ontology form (DSP-1139)

src/app/project/ontology/ontology-form/ontology-form.component.spec.ts, src/app/project/ontology/ontology-form/ontology-form.component.ts
resolves DSP-1139 s. comment <https://dasch.myjetbrains.com/youtrack/issue/DSP-1139#focus=Comments-4-3252.0-0>
=> chore(ontology): better regex for onto name (DSP-1139)

src/app/main/dialog/dialog.component.html, src/app/main/dialog/dialog.component.scss, src/app/workspace/resource/properties/properties.component.html, src/app/workspace/resource/properties/properties.component.ts
=> feat(resource): update resource's label (DSP-1801)

src/app/app.module.ts, src/app/workspace/intermediate/intermediate.component.html, src/app/workspace/intermediate/intermediate.component.scss, src/app/workspace/intermediate/intermediate.component.spec.ts, src/app/workspace/intermediate/intermediate.component.ts, src/app/workspace/results/results.component.html, src/app/workspace/results/results.component.ts
=> feat(workspace): add intermediate view (DSP-1834)

src/app/project/ontology/ontology-form/ontology-form.component.ts
=> chore(ontology): update create ontology tooltip for unique name (DSP-1139)

src/app/main/header/header.component.html, src/app/main/header/header.component.spec.ts, src/app/main/header/header.component.ts
This is a quick refactoring of the header component. Incl. the notification service instead the deprecated message component from DSP-UI after successful login. I thought I refactored it already, but it was still the old implementation. This PR fixes it now.
=> refactor(header): clean up code and use notification service after login

package-lock.json, package.json, src/app/app.module.ts, src/app/main/dialog/dialog.component.html, src/app/main/dialog/dialog.component.ts, src/app/workspace/intermediate/intermediate.component.html, src/app/workspace/intermediate/intermediate.component.spec.ts, src/app/workspace/intermediate/intermediate.component.ts, src/app/workspace/resource/project.service.spec.ts, src/app/workspace/resource/project.service.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts, src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts, src/app/workspace/resource/resource-link-form/resource-link-form.component.html, src/app/workspace/resource/resource-link-form/resource-link-form.component.spec.ts, src/app/workspace/resource/resource-link-form/resource-link-form.component.ts, src/app/workspace/results/results.component.html, src/app/workspace/results/results.component.ts
resolves DSP-1835 and resolves the issues mentioned in DSP-1820
After creating a `linkObj` resource it opens the new resource in a new tab. In this PR I have integrated the same logic when creating a new resource instance.
There's an "ugly" error from Angular lifecycle hook where I wasn't able to resolve it resp. when resolving it in DSP-APP we got another lifecycle hook error from DSP-UI and nothing works anymore. I hope to resolve the issue when moving DSP-UI components to DSP-APP (DSP-1857):
```console
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: 
Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.. 
Find more at https://angular.io/errors/NG0100
```
=> feat(resource): create link / collection resource (DSP-1835)

src/app/workspace/resource/incoming.service.ts, src/app/workspace/resource/properties/properties.component.html, src/app/workspace/resource/properties/properties.component.scss, src/app/workspace/resource/properties/properties.component.spec.ts, src/app/workspace/resource/properties/properties.component.ts
resolves DSP-1846
I added also a pagination to use in case there are more than 25 incoming links
=> feat(resource): display incoming links (DSP-1846)

package-lock.json, package.json
resolves DSP-1883
Since we use the latest version of DSP-API (v14) we should also use the latest version of DSP-JS (v4) which follows the breaking changes from DSP-API.
=> chore(deps): bump dsp-js to latest version (DSP-1883)

src/app/main/action/login-form/login-form.component.html, src/app/main/login/login.component.scss
=> chore(login): add autocomplete to login form (DSP-1892)

src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
=> fix(resource-instance-form): resource class name now updates correctly (DSP-1810)

src/app/main/directive/external-links.directive.ts
=> fix(links): trust external links (DSP-1904)

src/app/workspace/resource/properties/properties.component.html, src/app/workspace/resource/properties/properties.component.scss, src/app/workspace/resource/properties/properties.component.ts, src/assets/style/_elements.scss
=> fix(resource): increase width of space between entries of incoming links (DSP-1908)

src/app/main/services/component-communication-event.service.ts, src/app/workspace/results/list-view/list-view.component.ts, src/app/workspace/search/fulltext-search/fulltext-search.component.ts
=> refactor(fulltext-search): persist fulltext search term in input field (DSP-1674)

src/app/main/error/error-handler.service.ts, src/app/main/services/notification.service.ts, src/app/workspace/resource/resource.component.html
resolves DSP-1911
You can test it as follows:
- Start the app with the test-server configuration
- Open the following page: <http://0.0.0.0:4200/search/fulltext/Stygimoloch>
- If you're logged-in, you should see the correct error message from JS-Lib instead the 503 error mentioned in DSP-1910
Or
- Start the app with your local api stack environment
- Turn off the API
- You should see the 503 server error
=> fix(error): improve the current error handler in DSP-APP (DSP-1911)

.github/pull_request_template.md, src/app/project/ontology/ontology.component.html, src/app/project/ontology/ontology.component.scss, src/app/project/ontology/property-info/property-info.component.html, src/app/project/ontology/property-info/property-info.component.scss, src/app/project/ontology/property-info/property-info.component.spec.ts, src/app/project/ontology/resource-class-info/resource-class-info.component.html, src/app/project/ontology/resource-class-info/resource-class-info.component.scss, src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
=> feat(ontology): display id / name in property and class (DEV-37)

package-lock.json, package.json, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts, src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.spec.ts, src/app/workspace/search/advanced-search/search-select-ontology/search-select-ontology.component.spec.ts
=> fix(resource-instance-form): reload cached resource (DSP-1810)

src/app/app-init.service.ts, src/app/workspace/resource/representation/upload/upload-file.service.ts
=> refactor: iiif config refactor (DEV-162)

src/app/workspace/resource/representation/still-image/still-image.component.spec.ts, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts
=> refactor: only show image regions when on the annotations tab (DEV-146)

src/app/workspace/resource/representation/still-image/still-image.component.ts
=> feat(still-image): use the color of the color property for the line color (DEV-210)

src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html, src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts, src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html, src/assets/style/_viewer.scss
=> fix(text-value): display line breaks in read mode of paragraph text values (DEV-211)

src/app/main/services/component-communication-event.service.ts, src/app/system/projects/projects-list/projects-list.component.ts, src/app/workspace/search/fulltext-search/fulltext-search.component.ts
=> fix(fulltext-search): update projects list dropdown on new project creation (DEV-212)

src/app/workspace/resource/properties/properties.component.html, src/app/workspace/resource/properties/properties.component.ts, src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.html, src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.spec.ts, src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.ts
=> feat(properties): ckEditor Internal Links (DEV-118)

package-lock.json, src/app/main/dialog/dialog.component.html, src/app/system/projects/projects-list/projects-list.component.html, src/app/system/projects/projects-list/projects-list.component.ts, src/app/system/projects/projects.component.html, src/app/system/projects/projects.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json
=> fix(projects): correctly refresh projects list when activating/deactivating projects (DEV-230)

package-lock.json, package.json, src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts, src/app/project/list/list-item-form/list-item-form.component.ts
=> chore(lists): fix lists functionality that broke due to js-lib changes (DEV-273)

package-lock.json, package.json, src/app/app.module.ts, src/app/project/ontology/default-data/default-resource-classes.ts, src/app/workspace/resource/properties/properties.component.html, src/app/workspace/resource/representation/archive/archive.component.html, src/app/workspace/resource/representation/archive/archive.component.spec.ts, src/app/workspace/resource/representation/archive/archive.component.ts, src/app/workspace/resource/representation/file-representation.ts, src/app/workspace/resource/representation/upload/upload.component.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts, src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts, src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-resource-class/search-select-resource-class.component.spec.ts, src/assets/style/_elements.scss
=> feat(representation): add support for uploading and viewing archive files (DEV-18)

src/app/main/pipes/string-transformation/linkify.pipe.spec.ts, src/app/main/pipes/string-transformation/linkify.pipe.ts
=> fix(value): fix linkify pipe (DEV-270)

src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/specify-property-value.component.ts
=> fix(advanced search): update comparison operators in case of rich text (DEV-326)

src/app/workspace/resource/values/yet-another-date-value/date-value-handler/date-value-handler.component.html, src/app/workspace/resource/values/yet-another-date-value/date-value-handler/date-value-handler.component.ts
=> fix(date-value): do not submit in case of period button (DEV-373)

angular.json
In this PR I bring back the development configuration for faster building in `ng s` mode.
=> chore(angular): optimize ng s in dev mode

package-lock.json, package.json, src/app/project/ontology/default-data/default-properties.ts, src/app/project/ontology/ontology.service.spec.ts, src/app/project/ontology/ontology.service.ts, src/app/project/ontology/property-form/property-form.component.html, src/app/project/ontology/property-form/property-form.component.ts, src/app/project/ontology/property-info/property-info.component.html, src/app/project/ontology/property-info/property-info.component.ts, src/app/project/ontology/resource-class-info/resource-class-info.component.html, src/app/project/ontology/resource-class-info/resource-class-info.component.ts, src/assets/style/_ontology.scss
=> fix(ontology): support subproperty in ontology editor (DEV-332)

src/app/app-init.service.spec.ts, src/app/app-init.service.ts
=> fix(main): bug fix in configuration file in case of prod mode (DEV-491)

src/app/app.module.ts, src/app/main/declarations/admin-permissions.ts, src/app/main/pipes/string-transformation/title-from-camel-case.pipe.spec.ts, src/app/main/pipes/string-transformation/title-from-camel-case.pipe.ts, src/app/material-module.ts, src/app/system/projects/projects.component.ts, src/app/workspace/resource/permission-info/permission-info.component.html, src/app/workspace/resource/permission-info/permission-info.component.scss, src/app/workspace/resource/permission-info/permission-info.component.spec.ts, src/app/workspace/resource/permission-info/permission-info.component.ts, src/app/workspace/resource/properties/properties.component.html, src/app/workspace/resource/properties/properties.component.ts, src/assets/style/_mixins.scss, src/assets/style/main.scss
=> feat(resource): display permissions (DEV-454)

src/app/workspace/resource/permission-info/permission-info.component.ts
=> fix(permission-info): better permission string handling (DEV-537)

src/app/workspace/resource/permission-info/permission-info.component.scss, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts
resolves DEV-455
Resource viewer (and app) is broken if user doesn't have the necessary permission on still image file representation. In this case the representationsToDisplay fileValue is undefined. This PR resolves this issue.
=> fix(resource): resource viewer is broken if fileRepresentation has restricted view (DEV-455)

src/app/workspace/resource/representation/still-image/still-image.component.ts
=> fix(still-image): fix image displayed as black square (DEV-525)

src/app/workspace/resource/permission-info/permission-info.component.html, src/app/workspace/resource/permission-info/permission-info.component.ts, src/app/workspace/results/results.component.html
The cdk-overlay-scrollstrategy was not working correctly. The `reposition` attribute was not useful. With this PR it will close the info box as soon the user scrolls (in Safari). There is one bad behaviour which I was not able to resolve. The the scroll event closes the info box, the user has to click twice on the permission button, because the `isOpen` status is still set to true. I couldn't find a good example to resolve this.
=> fix(permission-info): close permission info on scrolling (DEV-552)

src/app/workspace/search/services/gravsearch-generation.service.spec.ts, src/app/workspace/search/services/gravsearch-generation.service.ts
=> fix(gravsearch): fix list value restriction (DEV-486)

package-lock.json, package.json, src/app/main/error/error-handler.service.spec.ts, src/app/main/error/error.component.spec.ts, src/app/user/user.component.spec.ts
=> chore(deps): bump js-lib to latest (DEV-669)

src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.scss, src/app/workspace/resource/representation/still-image/still-image.component.spec.ts, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/assets/style/_elements.scss
=> feat(still-image): IIIF URL copy button (DEV-524)

.gitignore, docs/requirements.txt, src/app/app.module.ts, src/app/main/dialog/dialog.component.html, src/app/main/dialog/dialog.component.ts, src/app/workspace/resource/representation/archive/archive.component.html, src/app/workspace/resource/representation/archive/archive.component.ts, src/app/workspace/resource/representation/audio/audio.component.html, src/app/workspace/resource/representation/audio/audio.component.scss, src/app/workspace/resource/representation/audio/audio.component.ts, src/app/workspace/resource/representation/document/document.component.html, src/app/workspace/resource/representation/document/document.component.ts, src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.html, src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.scss, src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.spec.ts, src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.ts, src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.spec.ts, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/app/workspace/resource/representation/upload/upload.component.ts, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts, src/app/workspace/resource/services/value-operation-event.service.ts
=> feat(replace-file): Replace Uploaded Files (DEV-684)

src/app/project/ontology/ontology.component.scss, src/app/project/ontology/property-info/property-info.component.html, src/app/project/ontology/property-info/property-info.component.scss
=> fix(ontology): display all classes in a property (DEV-564)

src/app/workspace/resource/properties/properties.component.html
=> style(resource): display class label of incoming link (DEV-568)

src/app/workspace/resource/operations/add-value/add-value.component.html, src/app/workspace/resource/operations/add-value/add-value.component.ts
=> fix(create-link-value): Create new resource instance to link when adding a new value (DEV-789)

src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts, src/app/workspace/resource/values/link-value/link-value.component.ts
=> feat(link-value): enter newly created link value automatically (DEV-687)

src/app/main/dialog/dialog.component.ts, src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.html, src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts, src/app/workspace/resource/values/link-value/link-value.component.ts
=> fix(link-value): re-validate form on cancel (DEV-611)

package-lock.json, package.json, src/app/project/ontology/default-data/default-resource-classes.ts, src/app/workspace/resource/properties/properties.component.ts, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/app/workspace/resource/resource-link-form/resource-link-form.component.spec.ts, src/app/workspace/resource/resource-link-form/resource-link-form.component.ts, src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/operator-constants.ts
=> refactor: use constants from js-lib directly (DEV-799)

src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts, src/assets/style/_elements.scss
=> fix(resource-instance-form): disable "next" button when form is not valid (DEV-803)

src/app/main/action/message/message.component.ts, src/app/main/action/sort-button/sort-button.component.ts, src/app/main/action/string-literal-input/string-literal-input.component.ts, src/app/main/directive/admin-image/admin-image.config.ts, src/app/main/directive/admin-image/admin-image.directive.ts, src/app/main/directive/existing-name/existing-name.directive.ts, src/app/main/header/header.component.spec.ts, src/app/project/project-form/project-form.component.ts, src/app/system/groups/groups-list/groups-list.component.html, src/app/user/user-form/password-form/password-form.component.html, src/app/user/user-form/user-form.component.html, src/app/user/user-form/user-form.component.ts, src/app/workspace/results/list-view/list-view.component.spec.ts, src/app/workspace/results/list-view/list-view.component.ts, src/app/workspace/search/advanced-search/advanced-search.component.ts, src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.ts, src/app/workspace/search/expert-search/expert-search.component.ts, src/app/workspace/search/fulltext-search/fulltext-search.component.ts, src/app/workspace/search/search-panel/search-panel.component.ts
=> refactor: clean up jsDocs and delete deprecated methods (DEV-741)

src/app/project/ontology/ontology.component.html, src/app/project/ontology/ontology.component.scss
resolves DEV-493
The full label will be shown in the tooltip:
=> style(ontology): crop loooong ontology labels (DEV-493)

src/app/workspace/resource/representation/archive/archive.component.ts, src/app/workspace/resource/representation/audio/audio.component.ts, src/app/workspace/resource/representation/document/document.component.ts, src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/app/workspace/resource/representation/video/video.component.ts, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts
resolves DEV-638
Especially in case of a book, where the incoming file representations have to be loaded first, it makes sense to display the whole resource when everything is ready.
https://user-images.githubusercontent.com/4253580/166705598-b29e402b-4762-4528-9877-36e99d54ea26.mov
=> feat(resource): better progress indicator handling in resource viewer (DEV-638)

src/app/workspace/resource/values/link-value/link-value.component.html, src/app/workspace/resource/values/link-value/link-value.component.ts
=> feat(link-value): Show message when no search results returned (DEV-846)

src/app/project/ontology/ontology.component.ts, src/app/project/ontology/property-form/property-form.component.html, src/app/project/ontology/property-form/property-form.component.spec.ts, src/app/project/ontology/property-form/property-form.component.ts
=> feat(ontology): select link class from all ontologies (DEV-688)

src/app/project/list/list-info-form/list-info-form.component.html, src/app/project/list/list-info-form/list-info-form.component.spec.ts, src/app/project/list/list-info-form/list-info-form.component.ts, src/app/project/list/list.component.html, src/app/project/list/list.component.ts, src/app/project/ontology/ontology.component.html, src/app/project/ontology/ontology.component.ts, src/app/workspace/resource/representation/av-timeline/av-timeline.component.ts
resolves DEV-926 and resolves issue with required comment in list root node
=> refactor(project): resolve issues in lists and with status 204

src/app/main/services/error-handler.service.ts, src/app/main/services/notification.service.ts, src/app/workspace/resource/resource.component.ts, src/app/workspace/results/list-view/list-view.component.ts, src/app/workspace/search/fulltext-search/fulltext-search.component.ts
=> feat(error): handle 504 timeout error with snackbar (DEV-751)

src/app/project/ontology/ontology.service.ts
=> fix(ontology): unsupported property type was displayed wrong (DEV-936)

src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.scss, src/app/workspace/resource/representation/still-image/still-image.component.spec.ts, src/app/workspace/resource/representation/video/video.component.html, src/app/workspace/resource/representation/video/video.component.scss, src/assets/style/_elements.scss
=> feat(representation)!: new navigation in still-image viewer (DEV-895)

src/app/main/services/error-handler.service.ts, src/app/main/services/notification.service.ts, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts, src/app/workspace/results/list-view/list-view.component.ts
=> fix(error): resolve error handler issues (DEV-938)

src/app/workspace/resource/properties/properties.component.html
=> chore(resource): display incoming links the same way as prop values (DEV-567)

package-lock.json, package.json, src/app/app.module.ts, src/app/main/status/status.component.ts, src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts, src/app/workspace/resource/representation/text/text.component.html, src/app/workspace/resource/representation/text/text.component.spec.ts, src/app/workspace/resource/representation/text/text.component.ts, src/app/workspace/resource/representation/upload/upload.component.html, src/app/workspace/resource/representation/upload/upload.component.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts, src/app/workspace/resource/resource.component.html, src/app/workspace/resource/resource.component.ts, src/assets/style/_elements.scss
=> feat(text-file): add support for text file representations (DEV-920)

src/app/project/ontology/ontology-form/ontology-form.component.html, src/app/project/ontology/property-form/property-form.component.html, src/app/project/ontology/resource-class-form/resource-class-form.component.html, src/app/project/project-form/project-form.component.html, src/app/workspace/resource/resource-link-form/resource-link-form.component.html, src/app/workspace/resource/values/boolean-value/boolean-value.component.html, src/app/workspace/resource/values/color-value/color-value.component.html, src/app/workspace/resource/values/date-value/date-value.component.html, src/app/workspace/resource/values/decimal-value/decimal-value.component.html, src/app/workspace/resource/values/geoname-value/geoname-value.component.html, src/app/workspace/resource/values/int-value/int-value.component.html, src/app/workspace/resource/values/interval-value/interval-value.component.html, src/app/workspace/resource/values/link-value/link-value.component.html, src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html, src/app/workspace/resource/values/text-value/text-value-as-xml/text-value-as-xml.component.html, src/app/workspace/resource/values/uri-value/uri-value.component.html
=> refactor(form): replace matAutosize by cdkAutosize (DEV-968)

src/app/project/ontology/resource-class-info/resource-class-info.component.html
=> fix(ontology): check if value exists without refreshing the page (DEV-923)

package-lock.json, package.json, src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts, src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts
=> feat(list): add support for deleting child node comments (DEV-965)

src/app/main/dialog/dialog.component.html, src/app/main/dialog/dialog.component.ts, src/app/project/ontology/resource-class-info/resource-class-info.component.html, src/app/project/ontology/resource-class-info/resource-class-info.component.ts, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html, src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
=> feat(resource): create new resource instance directly from ontology's class (DEV-959)

src/app/workspace/resource/values/link-value/link-value.component.ts
=> refactor(link-value): List all of a superclass's subclasses (DEV-997)

angular.json, src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.html, src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.spec.ts, src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.ts
=> fix(date-value-handler): Date value fix (DEV-392)

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/main/action/login-form/login-form.component.ts, src/app/project/project-form/project-form.component.ts, src/app/project/project.component.html, src/app/project/project.component.ts, src/app/system/project-tile/project-tile.component.html, src/app/system/project-tile/project-tile.component.scss, src/app/system/project-tile/project-tile.component.spec.ts, src/app/system/project-tile/project-tile.component.ts, src/app/system/projects/projects.component.html, src/app/system/users/users-list/users-list.component.html, src/app/system/users/users-list/users-list.component.spec.ts, src/app/system/users/users-list/users-list.component.ts, src/app/user/overview/overview.component.html, src/app/user/overview/overview.component.scss, src/app/user/overview/overview.component.spec.ts, src/app/user/overview/overview.component.ts, src/assets/style/_layout.scss, src/assets/style/_responsive.scss
=> feat(overview): add overview and project tile components (DEV-984)

src/app/main/action/login-form/login-form.component.ts
=> refactor(login-form): don't redirect sysAdmin after login (DEV-1153)

src/app/project/ontology/property-form/property-form.component.ts
resolves DEV-1089
The property form currently calls the `replaceGuiElement()` method any time a label or comment on a property is changed and since `salsah-gui:List` is no longer supported in the app as of https://github.com/dasch-swiss/dsp-app/pull/643, the `guiElement` of ListValue object types was always changed to `salsah-gui:Pulldown`. However, in the [API](https://docs.dasch.swiss/2022.07.02/DSP-API/03-apis/api-v2/ontology-information/#changing-the-gui-element-and-gui-attributes-of-a-property) (not specifically stated in the docs, see screenshot below), it's only possible to change the `guiElement` of a TextValue object type so we should only call `replaceGuiElement()` if the property is a TextValue and the `guiElement` is different from it's initial value.
screenshot from old …
=> fix(property-form): App changes "salsah-gui:List" to "salsah-gui:Pulldown" (DEV-1089)

src/app/workspace/resource/representation/archive/archive.component.html, src/app/workspace/resource/representation/archive/archive.component.scss, src/app/workspace/resource/representation/archive/archive.component.spec.ts, src/app/workspace/resource/representation/video/video.component.scss, src/assets/style/_elements.scss
=> feat(archive): new archive representation view (DEV-1084)

src/app/main/action/login-form/login-form.component.ts, src/app/workspace/resource/representation/archive/archive.component.html
=> fix(login-form): keep user on same page after login (DEV-1158)

src/app/workspace/resource/representation/document/document.component.html, src/app/workspace/resource/representation/document/document.component.scss, src/app/workspace/resource/representation/document/document.component.ts
=> feat(document): changes to pdf viewer (DEV-1149)

src/app/main/status/status.component.spec.ts, src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.html, src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.scss, src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts, src/app/project/beta/ontology-classes/ontology-classes.component.html, src/app/project/collaboration/collaboration.component.spec.ts, src/app/project/permission/permission.component.spec.ts, src/app/project/project.component.html, src/app/project/project.component.scss, src/app/project/project.component.ts, src/app/workspace/results/list-view/resource-list/resource-list.component.html, src/app/workspace/results/list-view/resource-list/resource-list.component.ts, src/assets/style/_layout.scss
=> feat(projects): changes to nav bar (DEV-1101)

src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.scss, src/app/workspace/resource/representation/still-image/still-image.component.spec.ts, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/app/workspace/resource/resource.component.html
=> feat(still-image): new still-image viewer (DEV-1150)

src/app/workspace/resource/representation/archive/archive.component.html, src/app/workspace/resource/representation/archive/archive.component.scss, src/app/workspace/resource/representation/audio/audio.component.html, src/app/workspace/resource/representation/audio/audio.component.scss, src/app/workspace/resource/representation/document/document.component.html, src/app/workspace/resource/representation/document/document.component.scss, src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.scss, src/assets/style/_elements.scss
=> style(file-representations): adjust styling of file representation components (DEV-1186)

src/app/workspace/resource/representation/video/video.component.html, src/app/workspace/resource/representation/video/video.component.scss, src/app/workspace/resource/representation/video/video.component.ts
=> feat(video): add download button and overlay to video player (DEV-1151)

src/app/project/list/list-info-form/list-info-form.component.html, src/app/project/list/list-info-form/list-info-form.component.ts
=> fix(list): hide title (DEV-1207)

src/app/workspace/resource/representation/archive/archive.component.ts, src/app/workspace/resource/representation/audio/audio.component.html, src/app/workspace/resource/representation/audio/audio.component.ts, src/app/workspace/resource/representation/document/document.component.ts, src/app/workspace/resource/representation/still-image/still-image.component.html, src/app/workspace/resource/representation/still-image/still-image.component.ts, src/app/workspace/resource/representation/text/text.component.ts, src/app/workspace/resource/representation/video/video.component.html, src/app/workspace/resource/representation/video/video.component.scss, src/app/workspace/resource/representation/video/video.component.ts
=> chore(file-representation): add credentials to all file download requests (DEV-1257)

src/app/workspace/resource/values/list-value/list-value.component.html, src/app/workspace/resource/values/list-value/list-value.component.spec.ts, src/app/workspace/resource/values/list-value/list-value.component.ts, src/assets/style/_viewer.scss
=> feat(list-value): show hierarchy of list node (DEV-1092)

angular.json, package.json, src/app/workspace/resource/resource.component.ts, src/config/config.staging-server.json, src/environments/environment.staging-server.ts
=> fix(resource): compound resource with restricted resources infinite loading (DEV-1114)

src/app/workspace/resource/values/int-value/int-value.component.html, src/app/workspace/resource/values/int-value/int-value.component.ts
=> fix(int-value): fix int-value validation (DEV-1277)

src/app/workspace/resource/resource.component.ts
=> fix(resource): fix properties sorting (DEV-1204)

src/app/user/overview/overview.component.spec.ts, src/app/user/overview/overview.component.ts
=> fix: make deactivated projects invisible for all except sysadmin (DEV-1261)

src/app/workspace/resource/properties/properties.component.ts
=> fix(properties): resolve 409 conflict (DEV-1336)

src/app/project/list/list-item-form/list-item-form.component.html, src/app/project/list/list-item-form/list-item-form.component.scss, src/app/project/list/list-item-form/list-item-form.component.spec.ts, src/app/project/list/list-item-form/list-item-form.component.ts, src/app/project/list/list-item/list-item.component.html, src/app/project/list/list-item/list-item.component.scss, src/app/project/list/list-item/list-item.component.spec.ts, src/app/project/list/list-item/list-item.component.ts, src/app/project/list/list.component.html, src/app/project/list/list.component.ts, src/app/project/project.component.html, src/app/project/project.component.ts, src/app/workspace/results/results.component.ts
resolves DEV-1343
The lists (within the list tab and on the sidenav) are visible for project member but all the CRUD operations regarding lists were hidden.
=> feat(lists): read mode project member (DEV-1343)

src/app/main/services/component-communication-event.service.ts, src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts, src/app/workspace/resource/properties/properties.component.ts, src/app/workspace/results/list-view/list-view.component.ts
=> fix(list-view): refresh list view after a resource is deleted or erased (DEV-1353)

src/app/project/ontology/ontology.component.ts
=> fix: Ontologies displayed twice (DEV-1325)

src/app/app-routing.module.ts, src/app/project/ontology/ontology.component.ts, src/app/project/project.component.ts
=> fix: Onto editor 404 error (DEV-1355)

src/app/workspace/resource/representation/video/video-preview/video-preview.component.ts
The number of lines should always be the next bigger integer not the closest smaller integer
resolves DEV-1513
=> Fix off by one error during calculation of number of lines in the matrix files

src/app/workspace/resource/representation/still-image/still-image.component.ts
Resolves DEV-1554.
Introduce new features:
- the viewers focus is limited to the image borders (no more zooming into black background). On zooming in and out the view got stuck sometimes and cut the image. The view now sticks to the images borders and centers back on zooming out.
- improve drag behaviour: direct/instant. No delay, no slow animations
- double click zooms in
- flick gestures are possible to drag the image
=> feat (still image component): view stays within image borders, instant drag, no delay, double click and flick enabled

src/app/workspace/results/list-view/list-view.component.ts
resolves DEV-1541
This is just small enhancement to distinguish between different states of no resources to display. The snack bar shows more precise info for the user that there is either nothing to display or he doesn't have the permission to see the resources.
To test it, must run JS-LIB in development mode via yalc from [this branch](https://github.com/dasch-swiss/dsp-js-lib/pull/480), or mian after the merge.
=> fix: fix gravsearch results infinite loading (DEV-1541)

Dockerfile
Bumping nginx-server version to newest version that brings in [cache-control headers that turn off caching](https://github.com/dasch-swiss/docker-nginx-server/commit/5d51c33c6f2daca73ba8ccf9ad80c7aa4aa27e20)
=> chore: bump nginx-server version

apps/dsp-app/src/app/project/ontology/property-form/property-form.component.html, apps/dsp-app/src/app/project/ontology/property-form/property-form.component.ts
Disable submit button after click and show progress spinner instead to prevent a double click and a double request.
resolves DEV-1932
=> feat(submit cardinnalities): disable double click

apps/dsp-app/src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/specify-property-value.component.spec.ts, apps/dsp-app/src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/specify-property-value.component.ts, apps/dsp-app/src/app/workspace/search/services/gravsearch-generation.service.spec.ts
=> feat: activate not-exists for link prop

apps/dsp-app/src/app/workspace/search/fulltext-search/fulltext-search.component.html, apps/dsp-app/src/app/workspace/search/fulltext-search/fulltext-search.component.spec.ts, apps/dsp-app/src/app/workspace/search/fulltext-search/fulltext-search.component.ts
=> chore(fulltext-search): filter out deactivated projects and system projects

Makefile
=> chore: fix ci

package.json
=> chore: allow access to app locally on host 0.0.0.0

apps/dsp-app/src/app/user/user-form/password-form/password-form.component.html, apps/dsp-app/src/app/user/user-form/password-form/password-form.component.ts
=> fix(password-form): add better error handling

apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/resource-class-property-info.component.html, apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-property-info/resource-class-property-info.component.scss, apps/dsp-app/src/styles.scss
=> feat(remove property menu): add skeleton to mat menu until content loaded

libs/vre/shared/assets/status-msg/src/lib/status-msg/statusMsg.ts
=> chore(msg text): Change notification message text for 404 not found

apps/dsp-app/src/app/workspace/resource/directives/text-value-html-link.directive.spec.ts, apps/dsp-app/src/app/workspace/resource/directives/text-value-html-link.directive.ts
Further behaviour:
- second mouse and middle mouse clicks defaults for non internal links
- middle mouse and second mouse clicks on internal links disabled/overridden (open internally)
resolves DEV-2529
=> fix (richtext component): Text is selectable

apps/dsp-app/src/app/main/services/sorting.service.spec.ts, apps/dsp-app/src/app/main/services/sorting.service.ts, apps/dsp-app/src/app/workspace/resource/properties/properties.component.ts
=> fix(sorting): sorts incoming links by res class then res label

apps/dsp-app/src/app/app-global.ts, apps/dsp-app/src/app/app-routing.module.ts, libs/vre/shared/app-config/src/index.ts, libs/vre/shared/app-config/src/lib/app-config/app-constants.ts
=> refactor(app-global, app-routing-module): Replaces string literals with constants

apps/dsp-app/src/app/main/dialog/dialog.component.html, apps/dsp-app/src/app/project/ontology/ontology-form/ontology-form.component.ts
=> fix(ontology form): remove the input decorator

libs/vre/advanced-search/src/lib/ui/property-form/property-form-list-value/property-form-list-value.component.html, libs/vre/advanced-search/src/lib/ui/property-form/property-form-list-value/property-form-list-value.component.scss, libs/vre/advanced-search/src/lib/ui/property-form/property-form-list-value/property-form-list-value.component.ts
=> feat(advanced-search): make list menu resemble a dropdown

apps/dsp-app/src/app/project/list/list-info-form/list-info-form.component.spec.ts, apps/dsp-app/src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts, apps/dsp-app/src/app/project/list/list-item-form/list-item-form.component.spec.ts, apps/dsp-app/src/app/project/ontology/property-form/property-form.component.spec.ts, apps/dsp-app/src/app/project/ontology/resource-class-form/resource-class-form.component.spec.ts, apps/dsp-app/src/app/project/project-form/project-form.component.spec.ts, apps/dsp-app/src/app/project/project.component.spec.ts, apps/dsp-app/src/app/user/account/account.component.spec.ts, apps/dsp-app/src/app/user/profile/profile.component.spec.ts, apps/dsp-app/src/app/user/user.component.spec.ts, apps/dsp-app/src/app/workspace/search/expert-search/expert-search.component.html, apps/dsp-app/src/app/workspace/search/expert-search/expert-search.component.spec.ts, apps/dsp-app/src/app/workspace/search/expert-search/expert-search.component.ts
=> feat(expert search): implement default gravsearch as placeholder

apps/dsp-app/src/app/main/help/help.component.ts
=> fix(app/help): fix links to releases

apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.ts
Need to subscribe to the observable to trigger the request, otherwise it will not be sent. The observable is lazy. Fix also for activating the project.
resolves DEV-2931
=> fix(activate/deactivate project): subscribe to the observable

apps/dsp-app/src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts, apps/dsp-app/src/app/project/project-base.ts, apps/dsp-app/src/app/workspace/results/list-view/list-view.component.ts
resolves loading exceptions when jumping to project resources using url after visiting another project before
=> fix: Project initialisation from url

apps/dsp-app/src/app/project/data-models/data-models.component.html, apps/dsp-app/src/app/project/data-models/data-models.component.ts
Also refactor some parts of the component
=> fix: add tooltip on non accessible list

apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.html, apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.ts, apps/dsp-app/src/app/workspace/resource/resource.component.html
and press the replace image button
resolves DEV-3200
=> fix(still image): User without permission can draw a region

apps/dsp-app/src/app/project/create-project-form-page/create-project-form-page.component.ts, libs/vre/shared/app-error-handler/src/lib/app-error-handler.ts, libs/vre/shared/app-string-literal/src/lib/multi-language-textarea.component.ts
=> fix: various errors

apps/dsp-app/src/app/app.component.ts, libs/vre/shared/app-analytics/src/lib/pendo-analytics/pendo-analytics.service.ts
=> fix: initialize pendo on app start

apps/dsp-app/src/app/app.module.ts, apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.html, apps/dsp-app/src/app/workspace/resource/values/third-party-iiif/iiif-url-validator.ts, apps/dsp-app/src/app/workspace/resource/values/third-party-iiif/third-party-iiif.component.html, apps/dsp-app/src/app/workspace/resource/values/third-party-iiif/third-party-iiif.component.scss, apps/dsp-app/src/app/workspace/resource/values/third-party-iiif/third-party-iiif.component.ts, apps/dsp-app/src/app/workspace/resource/values/third-party-iiif/third-party-iiif.ts
resolves DEV-3404,  DEV-3441, DEV-3334
=> feat: IIIf image edit component

apps/dsp-app/src/app/workspace/resource/representation/add-region-form/add-region-form.component.html, apps/dsp-app/src/app/workspace/resource/representation/add-region-form/add-region-form.component.scss, apps/dsp-app/src/app/workspace/resource/values/color-value/color-picker/color-picker.component.scss
=> fix: color picker style (DEV-3476)

apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.html, apps/dsp-app/src/app/workspace/resource/representation/still-image/still-image.component.ts, apps/dsp-app/src/app/workspace/resource/resource.component.html, apps/dsp-app/src/app/workspace/resource/resource.component.ts, libs/vre/shared/app-helper-services/src/lib/project.service.ts
=> fix: project member resource edit permissions (#DEV-3479)

.github/workflows/main.yml, Makefile, docs/user-guide/publication.md, docs/user-guide/user.md
check every PR if the docs comply with mkdocs and markdownlint
=> test(docs): add markdownlint and mkdocs CI checks

apps/dsp-app/src/app/workspace/resource/representation/upload/upload.component.ts, apps/dsp-app/src/config/config.0845-test-server.json, apps/dsp-app/src/config/config.dev-server.json, apps/dsp-app/src/config/config.dev.json, apps/dsp-app/src/config/config.ls-test-server.json, apps/dsp-app/src/config/config.prod.json, apps/dsp-app/src/config/config.stage-server.json, apps/dsp-app/src/config/config.test-server.json, libs/vre/shared/app-config/src/lib/app-config/app-config.service.spec.ts, libs/vre/shared/app-config/src/lib/app-config/app-config.service.ts, libs/vre/shared/app-config/src/lib/app-config/app-config.ts, libs/vre/shared/app-config/src/lib/app-config/dsp-ingest-config.ts, libs/vre/shared/app-resource-properties/src/lib/upload-file.service.ts, libs/vre/shared/app-resource-properties/src/lib/upload2.component.ts, package.json
- **add configuration for dsp-ingest server**
- **upload binaries to dsp-ingest instead of Sipi**
Needs https://github.com/dasch-swiss/dsp-js-lib/pull/639 to be merged, released and integrated for updating dsp-api resources correctly. 
For now I was able to test this locally by publish the dsp-js-lib for my machine using our built in [yalc](https://github.com/wclr/yalc) support:
```sh
> cd dsp-js-lib
> npm run yalc-publish
```
And import it into the app:
```sh
> cd dsp-das
> npm run yalc-add-lib
```
=> refactor: Use dsp-ingest for file upload (DEV-2628)

libs/vre/shared/app-representations/src/lib/region.service.ts, libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts, libs/vre/shared/app-resource-page/src/lib/resource-toolbar.component.ts
fix: highlighting image region after creating new one (#DEV-3700)
prevents from loading resource list if removed resource is region
=> fix: highlighting image region after creating new one (#DEV-3700) 

k6/Dockerfile.influxdb, k6/docker-compose.yml, k6/justfile, k6/options/options.js, k6/pages/resource-page.js, k6/pages/single-resource-page.js, k6/tests/first-page-load.js, k6/tests/load-resource.js, k6/tests/load-single-resource.js
- **feat**: Add dedicated project id for k6 cloud runs
- **feat**: Add test for a resource on a single page without databrowser
- **test**: Migrate tests to k6/browser 
- **fix**: Fixes local influxdb setup broken after last `influx-cli` release
=> test: Migrate tests to k6/browser which left experimental stage, run cloud test in dedicated project

.github/workflows/main.yml, .github/workflows/publish-from-branch.yml, package.json
There are still some GH registry leftovers which break publishing to Docker Hub.
=> chore: fix publishing to Docker Hub

package-lock.json, package.json
superseeds https://github.com/dasch-swiss/dsp-das/pull/1550
=> chore(deps-dev): bump cypress to 13.14.2 (fixes compatability with Firefox 130)

apps/dsp-app/cypress/e2e/project-member/resource-basic-member.cy.ts, apps/dsp-app/cypress/e2e/project-member/resource-project-admin.cy.ts, apps/dsp-app/cypress/support/commands/api-commands.ts, libs/vre/shared/app-representations/src/lib/still-image/still-image-helper.ts, libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts
=> fix: osd navigator 401 issue (DEV-4317)

.github/dependabot.yml
To address problematic updates in separate PRs the grouping is turned off for now and it will be turned on again after the updates.
=> chore(dependabot): temporarily change updates interval and remove grouping

libs/vre/shared/app-ontology/src/lib/ontology.component.ts, libs/vre/shared/app-ontology/src/lib/resource-class-info/resource-class-info.component.html, libs/vre/shared/app-ontology/src/lib/resource-class-info/resource-class-info.component.ts
=> fix: use correct class and translate the label (DEV-4373)

.github/dependabot.yml, package-lock.json, package.json
This PR includes:
- improve nx-deps pattern
- bump and install optional nx-deps
- add angular group and ignore rule for angular and nx dependencies group
=> chore: improve Dependabot rules and grouping

libs/vre/resource-editor/resource-editor/src/lib/compound/compound.service.ts, libs/vre/resource-editor/resource-editor/src/lib/resource.component.ts
…ming resource aka page
resolves DEV-4171
=> fix: update annotations tab when switching to a compound without page (DEV-4171)

libs/vre/resource-editor/representations/src/lib/edit-third-party-iiif-form/edit-third-party-iiif-form.component.ts, libs/vre/resource-editor/representations/src/lib/still-image/still-image.component.ts, libs/vre/resource-editor/representations/src/lib/third-party-iiif/third-party-iiif.component.ts
=> fix: save and replace external IIIF image (DEV-4227)

.github/dependabot.yml
=> chore: divide packages into Dependabot groups

package-lock.json, package.json
=> fix: rollback ckeditor version to not include footnotes plugin

.github/workflows/codeql-analysis.yml
Reason:
> Analyze (javascript)
> CodeQL Action major versions v1 and v2 have been deprecated. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
=> chore: update github/codeql-action to v3

apps/dsp-app/src/main.ts
The list of excluded servers should reduce Sentry quota.
=> chore: add environments list excluded from tracking by Sentry
